### ISSUE TITLE
custom r99 recoil pattern enhancement

### ISSUE THREAD

**Issue by Murren7** [mgsweet/Apex-NoRecoil-2021#1]

**Comment by Murren7** [comment]
Try my 99 recoil pattern,but i use  modifier:=3.4/sens

global R99_INTERVAL := 52
global R99_RECOILS := [[-1.6, 7], [0.5, 6.2], [2.3, 4.9], [-1.8, 10], [-2.8, 12.5]
                        , [-3.3, 9], [-7, 8], [-2, 7], [0, 9], [4, 8]
                        , [4.5, 7], [1, 7], [1, 6], [-1.1, 5.5], [-4, -1]
                        , [-4, 2.55], [-3, 1], [3, 1], [4, 2.5], [6, 1],
                        , [5, 2], [4, 3], [-6, 1], [-3, 1], [-4, 0]
                        , [-2, 0]]

**Comment by mgsweet** [comment]
Could u tell me why u change the interval to 52?
If the data in [Weapon Wiki](https://apexlegends.fandom.com/wiki/Weapon) is correct, 60s / 1080 is about 55ms.
I will try your setting anyway but may not change the code:)

**Comment by mgsweet** [comment]
Your setting is pretty good (better than mine XD). It works on my sens(5) as well. Thanks for your contribution.

**Comment by mgsweet** [comment]
Your setting is pretty good (better than mine XD). It works on my sens(5) as well. Thanks for your contribution.

**Comment by Murren7** [comment]
I think there is different interval after each bullet,so i use old script with binds cuz i made almost perfect recoil for each weapon with different intervals.You can use this website to test and make perfect recoil https://apexlegendsrecoils.online/

**Comment by Murren7** [comment]
modifier:=3.4/sens

**Comment by mgsweet** [comment]
Sure, just send me the patterns and I will add them on the weekend. 













At 2021-07-14 03:42:42, "Murren7" ***@***.***> wrote:

Hello, can you add more weapons please? Volt,alternator,re43 etc. I can share almost perfect patterns for all weapons

**Comment by mgsweet** [comment]
@Murren7 could you send me all your patterns? including the new gun Ramage.

**Comment by mgsweet** [comment]
Check: https://github.com/mgsweet/Apex-NoRecoil-2021/issues/3
