### ISSUE TITLE
New script feature.

### ISSUE THREAD

**Issue by Igors7999** [mgsweet/Apex-NoRecoil-2021#101]
This will be interesting to test.  Make when you hit an enemy the mouse sensitivity decreases.  This will help you hit the enemy more accurately.  This can be done with the help of triggers on the pop-up numbers (their colors) when you hit an enemy.  when the damage numbers appear on the screen, the mouse sensitivity will decrease.  You will also need to adapt the recoil when firing. Pls try to make it.

**Comment by fatinghenji** [comment]
Don't think it's a good proposition, it will make it hard to hit enemies like those traveling on the zip line / flying in the air

**Comment by Igors7999** [comment]
Maybe make it possible to disable it by double-clicking the right mouse button?
