### ISSUE TITLE
The projects have been moved to taobao for sale by someone

### ISSUE THREAD

**Issue by RedPhosphorus-L** [mgsweet/Apex-NoRecoil-2021#102]
https://item.taobao.com/item.htm?id=662897135651&ali_refid=a3_430673_1006:1406860181:N:JCXldndPa3mqXTHrD6GWrw%3D%3D:72fff3a2ce94ca555cd113ac0895db39&ali_trackid=1_72fff3a2ce94ca555cd113ac0895db39&spm=a2e0b.20350158.31919782.2&mt=

**Comment by mgsweet** [comment]
As long as they follow [GPL-3.0 license](https://github.com/mgsweet/Apex-NoRecoil-2021/blob/main/LICENSE), it's fine.
