### ISSUE TITLE
喷火轻机枪的无后座经常不生效

### ISSUE THREAD

**Issue by xyxywan** [mgsweet/Apex-NoRecoil-2021#106]
测试了平行和R301,都没问题，但是喷火轻机枪的无后座很难触发，或者运气触发了无后座，换完弹匣后效果又没了，不知道是什么原因，使用的脚本是AHK/src/apexmaster.ahk

**Comment by 233Isaac** [comment]
赛季更新 脚本还没更新吧

**Comment by baoc2** [comment]
對，這賽季的腳本還沒更新
你要是看得懂代碼的話可以先自行把supplydrop部分裡的噴火槍全移到heavy裡去就能使用了

**Comment by jkj06921** [comment]
想問一下,我啟動不管是S13別人的AHK,
還是[mgsweet]的AHK,在遊戲上都沒有反應,
但我平常使用的AHK腳本在其他遊戲上可以使用,
是什麼部分可能造成沒有反應嗎?

**Comment by baoc2** [comment]
> 想問一下,我啟動不管是S13別人的AHK, 還是[mgsweet]的AHK,在遊戲上都沒有反應, 但我平常使用的AHK腳本在其他遊戲上可以使用, 是什麼部分可能造成沒有反應嗎?

你是不是有用Nvidia Filter或Reshade等調色類的濾鏡? 這些都要關掉不然就要自己抓顏色

**Comment by jkj06921** [comment]
> > 想問一下,我啟動不管是S13別人的AHK, 還是[mgsweet]的AHK,在遊戲上都沒有反應, 但我平常使用的AHK腳本在其他遊戲上可以使用, 是什麼部分可能造成沒有反應嗎?
> 
> 你是不是有用Nvidia Filter或Reshade等調色類的濾鏡? 這些都要關掉不然就要自己抓顏色

我是用AMD的卡,也沒調色調過,不過有帶icc,不知道跟這有沒有關係?

**Comment by baoc2** [comment]
> > > 想問一下,我啟動不管是S13別人的AHK, 還是[mgsweet]的AHK,在遊戲上都沒有反應, 但我平常使用的AHK腳本在其他遊戲上可以使用, 是什麼部分可能造成沒有反應嗎?
> > 
> > 
> > 你是不是有用Nvidia Filter或Reshade等調色類的濾鏡? 這些都要關掉不然就要自己抓顏色
> 
> 我是用AMD的卡,也沒調色調過,不過有帶ICC Profile,不知道跟這有沒有關係?

開著嗎? 你關掉試試

**Comment by jkj06921** [comment]
> > > > 想問一下,我啟動不管是S13別人的AHK, 還是[mgsweet]的AHK,在遊戲上都沒有反應, 但我平常使用的AHK腳本在其他遊戲上可以使用, 是什麼部分可能造成沒有反應嗎?
> > > 
> > > 
> > > 你是不是有用Nvidia Filter或Reshade等調色類的濾鏡? 這些都要關掉不然就要自己抓顏色
> > 
> > 
> > 我是用AMD的卡,也沒調色調過,不過有帶ICC Profile,不知道跟這有沒有關係?
> 
> 開著嗎? 你關掉試試

我嘗試看看,因為鍵盤 跟 滑鼠指令的ahk如果沒問題,
也許就真的是類似色塊不一樣的可能性.

**Comment by mgsweet** [comment]
Solved: https://github.com/mgsweet/Apex-NoRecoil-2021/pull/103
