### ISSUE TITLE
关于更高灵敏度的设置

### ISSUE THREAD

**Issue by Hirotonx** [mgsweet/Apex-NoRecoil-2021#107]
我想调整大于5.0的灵敏度请问我该更改哪部分的代码

**Comment by VerTox** [comment]
If you use AHK version, you need to change that string https://github.com/mgsweet/Apex-NoRecoil-2021/blob/main/AHK/src/gui.ahk#L28

**Comment by Hirotonx** [comment]
> If you use AHK version, you need to change that string https://github.com/mgsweet/Apex-NoRecoil-2021/blob/main/AHK/src/gui.ahk#L28
The higher sensitivity of the gui adjustment cannot be applied to  Apex

**Comment by Hirotonx** [comment]
> 如果使用 AHK 版本，则需要更改该字符串 https://github.com/mgsweet/Apex-NoRecoil-2021/blob/main/AHK/src/gui.ahk#L28

> If you use AHK version, you need to change that string https://github.com/mgsweet/Apex-NoRecoil-2021/blob/main/AHK/src/gui.ahk#L28

SRY This is only in some cases that the higher sensitivity will fail, and it can be used successfully after restarting the computer
