### ISSUE TITLE
Pattern generator

### ISSUE THREAD

**Issue by filen1** [mgsweet/Apex-NoRecoil-2021#11]
https://github.com/CharlesDankoff/ultra_secret_scripts 

see pattern_generator.py
edit with notepad++  to your sens and your modifier
- stand as far away from wall in apex as you can while still seeing impacts from bullets
- unload bullets into wall
- return ads to original position and screenshot
- open paint and zoom 2x to get the spray pattern enlarged
- use pattern_generator.py created by CharlesDankoff 
- f4 to activate then click all the impact marks
- f10 to save the tracked_pattern.txt
- convert the X.XXXXXXXXXXX into X.X and script layout

Sorry, Im new to Github idk where to place something like this, but I saw you two were unaware.

**Comment by krampus-nuggets** [comment]
Thanks @filen1 
I was actually searching UC trying to find a pattern generator and I couldn't see any, guess I'm just a dunce lol
Looks interesting, I'll have a look. Anything to save me from doing pattern prediction😬

**Comment by Lobfly** [comment]
nice bro,I can make my own pattern and script now

**Comment by filen1** [comment]
> Thanks @filen1
> I was actually searching UC trying to find a pattern generator and I couldn't see any, guess I'm just a dunce lol
> Looks interesting, I'll have a look. Anything to save me from doing pattern prediction😬

Yes he posted there, it took hours of searching (stalking profiles posts) to find it. I also forgot to mention the resulting pattern needs to be divided by 2 since you zoom x2 but this is mentioned in the pattern_generator.py comments.

There is a python plugin for notepad++ so you can divide the whole tracked_pattern file by 2
It was created(I believe) by Toto on stackoverflow with a [tutorial](https://stackoverflow.com/questions/62256029/divide-all-numbers-in-a-text-file-by-2)

**Comment by mgsweet** [comment]
cool. will add u to the contributor list later @filen1 XD

**Comment by mgsweet** [comment]
I just check the script and quit. It still need lots of work to do so. Lazy.

**Comment by mgsweet** [comment]
@all-contributors please add @filen1 for pattern-contributor

**Comment by mgsweet** [comment]
@all-contributors please add @filen1 for data

**Comment by krampus-nuggets** [comment]
I'm already working on the pattern-generator tool, the bulk of the work is done. The remaining work is just to tweak logic so that the data it generates is directly usable in both the AHK and Python scripts. It should be part of my next pull request.

**Comment by krampus-nuggets** [comment]
The pattern-tracker tool has been created and added to the project. Additional info below:

* The actual tool - https://github.com/mgsweet/Apex-NoRecoil-2021/blob/main/python/modules/pattern_tracker.py
* Please refer to the README on how to use the tool - https://github.com/mgsweet/Apex-NoRecoil-2021/tree/main/python
