### ISSUE TITLE
Weapon Color (Filters)

### ISSUE THREAD

**Issue by Nekomimis** [mgsweet/Apex-NoRecoil-2021#112]
Anyone knows how to convert it to the 0x prefix? I tried doing the normal RGB to Hexadecimal but it didn't work unless it's the wrong color. Since I prefer using filters to see better, the color would change even if it's a slight chance.

Currently, the RGB to Hexadecimal is e.g #FFFFFF and not 0xFFFFFF. (yes, if it's a pure white or black, it's just 000000 or FFFFFF)
Take Hex Color #90643C for Light Weapons, i tried putting 0x90643C but it doesn't work.

https://imgur.com/a/XVyggu3 here

**Comment by mgsweet** [comment]
Try BGR(revert RGB）

**Comment by Nekomimis** [comment]
> 

How do i do that though? I'm not biog of a coder ;-;

**Comment by mgsweet** [comment]
@Nekomimis For example,
RGB: 0x90643C
BGR: 0x3C6490
