### ISSUE TITLE
游戏被封禁

### ISSUE THREAD

**Issue by Astrov0** [mgsweet/Apex-NoRecoil-2021#113]
就算改了uuid，使用脚本一小时之内必被封
我不知道这个脚本存在的意义是什么。。。

**Comment by LaxdalGe** [comment]
你用的哪个版本？
python还是AHK？

**Comment by LaxdalGe** [comment]
文件夹里有hyde.dll一般就没问题，可以隐藏AHK进程

**Comment by Astrov0** [comment]
版本1.2.9，AHK编译成exe的，AHK进程怎么隐藏啊？？

**Comment by Astrov0** [comment]
> 文件夹里有hyde.dll一般就没问题，可以隐藏AHK进程

版本1.2.9，AHK编译成exe的，AHK进程怎么隐藏啊？？

**Comment by Astrov0** [comment]
> 文件夹里有hyde.dll一般就没问题，可以隐藏AHK进程

哦，我理解错你的意思了，用的时候我看了任务管理器进程是被隐藏了，但是游戏最终还是会被封禁。一般也就是一到两个小时之内就被封了

**Comment by LaxdalGe** [comment]
可能是新版本增强了检测吧

**Comment by LaxdalGe** [comment]
是封限时吗？还是永久？

**Comment by Astrov0** [comment]
> 是封限时吗？还是永久？

永久的，说我作弊

**Comment by LaxdalGe** [comment]
不好说

**Comment by LaxdalGe** [comment]
等几天看看别人的情况吧，有可能跟系统有关系

**Comment by Astrov0** [comment]
> 等几天看看别人的情况吧，有可能跟系统有关系

我觉得就是脚本被检测到了吧，系统我是win11。。。还好我用的小号测试的，要不然直接被ban了

**Comment by LaxdalGe** [comment]
哦哦还好是小号，先观望观望吧

**Comment by Astrov0** [comment]
> 哦哦还好是小号，先观望观望吧

你是开发者吗，没有多少人讨论啊这里，还说都是外国人

**Comment by LaxdalGe** [comment]
https://github.com/PetrosPastor/Apex-AimAssist-NoRecoil-2022
我不是，我也在找可以用的辅助

**Comment by LaxdalGe** [comment]
你可以看看这个，这个项目有些日子没维护了
是一个颜色识别自瞄，我打算开个小号试试

**Comment by Astrov0** [comment]
> https://github.com/PetrosPastor/Apex-AimAssist-NoRecoil-2022 我不是，我也在找可以用的辅助

这个我也看过，里面就说了，是因为AHK被检测到了，导致被ban

**Comment by Astrov0** [comment]
> 你可以看看这个，这个项目有些日子没维护了 是一个颜色识别自瞄，我打算开个小号试试

试试倒是可以试试，APEX这游戏，同一个机器被封多少个账号会被ban机器码啊？？我就怕机器码被ban了

**Comment by LaxdalGe** [comment]
它应该不是看封多少次ban机器码的，而是作弊的严重程度

**Comment by LaxdalGe** [comment]
我已经有五六个小号被封了

**Comment by LaxdalGe** [comment]
目前还是大号还是没有问题

**Comment by Astrov0** [comment]
> 我已经有五六个小号被封了

woc 那你这测试有点疯狂啊

**Comment by Astrov0** [comment]
> 目前还是大号还是没有问题

我去试试，刚刚那个，那个我还没试过。

**Comment by LaxdalGe** [comment]
https://updown.ninja/download/j8Xvl0DVdImNUUD

**Comment by LaxdalGe** [comment]
> > 我已经有五六个小号被封了
> 
> woc 那你这测试有点疯狂啊

害，都是steam的号，注册一个不到半分钟，就是每次都要过新手教程很烦

**Comment by LaxdalGe** [comment]
我刚刚去测试了一下，PetrosPastor的那个基本用不了，就是有好多功能的那个，然后我上面发的那个链接里的勉强可以用（恐怕是目前最好的选择了），他只有金镜才能生效，而且压强压得太多了导致一直在打下半身。目前并没有更好的解决办法，我在想能不能研究一下他是的脚本然后修改一下，反正目前就这样了🤔

**Comment by LaxdalGe** [comment]
我大概玩了两个小时了，还没有封号

**Comment by Astrov0** [comment]
> 我大概玩了两个小时了，还没有封号

这个有点离谱啊，比原版都nb，直接锁红色啊！！

**Comment by Astrov0** [comment]
> 我刚刚去测试了一下，PetrosPastor的那个基本用不了，就是有好多功能的那个，然后我上面发的那个链接里的勉强可以用（恐怕是目前最好的选择了），他只有金镜才能生效，而且压强压得太多了导致一直在打下半身。目前并没有更好的解决办法，我在想能不能研究一下他是的脚本然后修改一下，反正目前就这样了🤔

这个比原版都，nb，目前玩了一个小时，快两个小时，没封，而且他这个还锁红色，贼离谱，压枪刚刚好。。。

**Comment by LaxdalGe** [comment]
建议把压强数值调低一下，因为锁红会锁在身体下部
更改方法：
在pattern文件夹里找到想改的枪械，第一个数字是左右方向一般不用动，第二个是上下压枪，可以没三行调低一点，最后一个数字是射速一般也不用动。
`0,0,14.4
-1,1,14.4
0,2,14.4
1,0,14.4
-1,0,14.4
1,3,14.4
1,0,14.4
-1,1,14.4
0,-1,14.4
2,3,14.4
1,-1,14.4
-1,1,14.4
-1,2,14.4
1,1,14.4
-1,1,14.4
-1,3,14.4
0,1,14.4
1,1,14.4
-1,1,14.4
-3,5,14.4
0,0,14.4
-1,2,14.4
-2,1,14.4
-1,2,14.4
-1,1,14.4
-2,1,14.4
0,1,14.4
-1,1,14.4
0,-1,14.4
-1,3,14.4
1,0,14.4
-1,1,14.4
2,2,14.4
2,1,14.4
0,1,14.4
2,2,14.4
2,2,14.4
0,0,14.4
0,1,14.4
1,3,14.4
0,-1,14.4
0,2,14.4
1,2,14.4
2,1,14.4
-2,2,14.4
0,0,14.4
0,-3,14.4
-1,2,14.4
1,0,14.4
-5,-3,14.4
0,0,14.4
0,0,14.4
-2,1,14.4
0,0,14.4
-1,0,14.4
-2,1,14.4
0,-1,14.4
-1,1,14.4
0,0,14.4
4,1,14.4
0,-1,14.4
0,1,14.4
1,0,14.4
2,-2,14.4
0,0,14.4
2,1,14.4
2,0,14.4
0,0,14.4
2,2,14.4
2,-2,14.4
0,0,14.4
1,3,14.4
2,0,14.4
0,0,14.4
-1,0,14.4
0,-1,14.4
0,-1,14.4
-1,1,14.4
-2,-1,14.4
-2,-1,14.4
0,-1,14.4
0,0,14.4
-3,0,14.4
-2,-2,14.4
0,1,14.4
-1,0,14.4
1,-3,14.4
-1,0,14.4
2,1,14.4
2,-1,14.4
1,1,14.4
`

**Comment by LaxdalGe** [comment]
我还在完善，打算加入一个寻雪猎犬开大时的追踪，思路是： 检测“Z"键，当按下时把color-aim程序杀掉，然后运行大招颜色识别的程序，开始计时（大招持续时间），结束之后再把大招颜色识别程序杀掉然后运行正常的color-aim

**Comment by Astrov0** [comment]
> 我还在完善，打算加入一个寻雪猎犬开大时的追踪，思路是： 检测“Z"键，当按下时把color-aim程序杀掉，然后运行大招颜色识别的程序，开始计时（大招持续时间），结束之后再把大招颜色识别程序杀掉然后运行正常的color-aim

害，这个脚本，两小时封了

**Comment by LaxdalGe** [comment]
啊？！！！

**Comment by LaxdalGe** [comment]
我小号大概玩了五个小时了

**Comment by LaxdalGe** [comment]
放一晚上看看，明天早上会不会封

**Comment by Astrov0** [comment]
> 我小号大概玩了五个小时了

有无QQ 别在这里聊了

**Comment by LaxdalGe** [comment]
3336866916

**Comment by Astrov0** [comment]
> 放一晚上看看，明天早上会不会封

怪尴尬的

**Comment by LaxdalGe** [comment]
哈哈哈

**Comment by fatinghenji** [comment]
如果在使用之前仔细阅读过[#72](https://github.com/mgsweet/Apex-NoRecoil-2021/issues/72#issuecomment-1005336409) ，就不会有这么长的无用讨论。
我使用这个脚本已经有1月多，一直以来非常稳定

**Comment by Astrov0** [comment]
> 如果在使用之前仔细阅读过[#72](https://github.com/mgsweet/Apex-NoRecoil-2021/issues/72#issuecomment-1005336409) ，就不会有这么长的无用讨论。 我使用这个脚本已经有1月多，一直以来非常稳定

很抱歉，我就是按照步骤做的，自己构建exe，而且也换了uuid。但是还是被封禁了！！

**Comment by fatinghenji** [comment]
> > 如果在使用之前仔细阅读过[#72](https://github.com/mgsweet/Apex-NoRecoil-2021/issues/72#issuecomment-1005336409) ，就不会有这么长的无用讨论。 我使用这个脚本已经有1月多，一直以来非常稳定
> 
> 很抱歉，我就是按照步骤做的，自己构建exe，而且也换了uuid。但是还是被封禁了！！

重新编辑了，可以参考我的使用方案

**Comment by kazuhalfsugar** [comment]
我从2021年开始使用基于autohotkey的后座力削弱，mgsweet的项目中内置了ahkider以确保安全，我从未使用过exe版本，也没有在同一账户中游戏被禁止。
如果要在你的账户中进行绝对安全的游戏，你也可以尝试使用罗技Ghub的主动配置文件来减少后坐力，以下是我使用的代码。它可以在计算机启动时自动运行，并且仅在apex运行时自动激活，因为它绑定的激活按键是`Numlock`。
（基于dpi800，游戏中灵敏度2.0，开镜灵敏度1.0）
```function OnEvent(event, arg)
if (event == "PROFILE_ACTIVATED") then
EnablePrimaryMouseButtonEvents(true)
end
if IsKeyLockOn("numlock")then
if (event == "MOUSE_BUTTON_PRESSED" and arg == 1)then
if IsMouseButtonPressed(3)then
repeat
MoveMouseRelative(-5, 6)
Sleep(10)
MoveMouseRelative(5, -5)
Sleep(10) 
MoveMouseRelative(5, 6)
Sleep(10)
MoveMouseRelative(-5, -5)
Sleep(10)
until not IsMouseButtonPressed(1)
end
end
end
```
当你按住右键射击时，这个配置文件会抖动鼠标，并实现了一种叫做 "后坐力平滑 "的机制，以在apex中减少后坐力，据我所知，没有因为使用ghub而被禁止的案例。
但它不能帮助你进行臀部射击，也不能帮助你进行Hemlok自动射击，所以我在大多数情况下更喜欢使用autohotkey。
我不认为瞄准器是个好主意，它改变了你的射击习惯，所以你无法适应其他射击游戏，只要在apex使用减少后坐力就可以减少你的训练时间XD

**Comment by Astrov0** [comment]
> 我从2021年开始使用基于autohotkey的后座力削弱，mgsweet的项目中内置了ahkider以确保安全，我从未使用过exe版本，也没有在同一账户中游戏被禁止。 如果要在你的账户中进行绝对安全的游戏，你也可以尝试使用罗技Ghub的主动配置文件来减少后坐力，以下是我使用的代码。它可以在计算机启动时自动运行，并且仅在apex运行时自动激活，因为它绑定的激活按键是`Numlock`。 （基于dpi800，游戏中灵敏度2.0，开镜灵敏度1.0）
> 
> ```
> if (event == "PROFILE_ACTIVATED") then
> EnablePrimaryMouseButtonEvents(true)
> end
> if IsKeyLockOn("numlock")then
> if (event == "MOUSE_BUTTON_PRESSED" and arg == 1)then
> if IsMouseButtonPressed(3)then
> repeat
> MoveMouseRelative(-5, 6)
> Sleep(10)
> MoveMouseRelative(5, -5)
> Sleep(10) 
> MoveMouseRelative(5, 6)
> Sleep(10)
> MoveMouseRelative(-5, -5)
> Sleep(10)
> until not IsMouseButtonPressed(1)
> end
> end
> end
> ```
> 
> 当你按住右键射击时，这个配置文件会抖动鼠标，并实现了一种叫做 "后坐力平滑 "的机制，以在apex中减少后坐力，据我所知，没有因为使用ghub而被禁止的案例。 但它不能在进行臀部射击帮助你，也不能帮助你进行Hemlok自动射击，所以我在大多数情况下更喜欢使用autohotkey。 我不认为瞄准器是个好主意，它改变了你的射击习惯，所以你无法适应其他射击游戏，只要在apex使用减少后坐力就可以减少你的训练时间XD

谢谢兄弟！！这个好啊，罗技ghub脚本压枪确实不会被封。我之前也一直在用，就是只能垂直压枪，你这个是抖动压枪，厉害！

**Comment by Astrov0** [comment]
> 我从2021年开始使用基于autohotkey的后座力削弱，mgsweet的项目中内置了ahkider以确保安全，我从未使用过exe版本，也没有在同一账户中游戏被禁止。 如果要在你的账户中进行绝对安全的游戏，你也可以尝试使用罗技Ghub的主动配置文件来减少后坐力，以下是我使用的代码。它可以在计算机启动时自动运行，并且仅在apex运行时自动激活，因为它绑定的激活按键是`Numlock`。 （基于dpi800，游戏中灵敏度2.0，开镜灵敏度1.0）
> 
> ```
> if (event == "PROFILE_ACTIVATED") then
> EnablePrimaryMouseButtonEvents(true)
> end
> if IsKeyLockOn("numlock")then
> if (event == "MOUSE_BUTTON_PRESSED" and arg == 1)then
> if IsMouseButtonPressed(3)then
> repeat
> MoveMouseRelative(-5, 6)
> Sleep(10)
> MoveMouseRelative(5, -5)
> Sleep(10) 
> MoveMouseRelative(5, 6)
> Sleep(10)
> MoveMouseRelative(-5, -5)
> Sleep(10)
> until not IsMouseButtonPressed(1)
> end
> end
> end
> ```
> 
> 当你按住右键射击时，这个配置文件会抖动鼠标，并实现了一种叫做 "后坐力平滑 "的机制，以在apex中减少后坐力，据我所知，没有因为使用ghub而被禁止的案例。 但它不能在进行臀部射击帮助你，也不能帮助你进行Hemlok自动射击，所以我在大多数情况下更喜欢使用autohotkey。 我不认为瞄准器是个好主意，它改变了你的射击习惯，所以你无法适应其他射击游戏，只要在apex使用减少后坐力就可以减少你的训练时间XD

我试了一下，ghub驱动里报错。attempt to call a nil value Line Number:1

**Comment by mgsweet** [comment]
Pls discuss this topic in https://github.com/mgsweet/Apex-NoRecoil-2021/issues/72. Thanks.

**Comment by kazuhalfsugar** [comment]
> > 我从2021年开始使用基于autohotkey的后座力削弱，mgsweet的项目中内置了ahkider以确保安全，我从未使用过exe版本，也没有在同一账户中游戏被禁止。 如果要在你的账户中进行绝对安全的游戏，你也可以尝试使用罗技Ghub的主动配置文件来减少后坐力，以下是我使用的代码。它可以在计算机启动时自动运行，并且仅在apex运行时自动激活，因为它绑定的激活按键是`Numlock`。 （基于dpi800，游戏中灵敏度2.0，开镜灵敏度1.0）
> > ```
> > if (event == "PROFILE_ACTIVATED") then
> > EnablePrimaryMouseButtonEvents(true)
> > end
> > if IsKeyLockOn("numlock")then
> > if (event == "MOUSE_BUTTON_PRESSED" and arg == 1)then
> > if IsMouseButtonPressed(3)then
> > repeat
> > MoveMouseRelative(-5, 6)
> > Sleep(10)
> > MoveMouseRelative(5, -5)
> > Sleep(10) 
> > MoveMouseRelative(5, 6)
> > Sleep(10)
> > MoveMouseRelative(-5, -5)
> > Sleep(10)
> > until not IsMouseButtonPressed(1)
> > end
> > end
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 当你按住右键射击时，这个配置文件会抖动鼠标，并实现了一种叫做 "后坐力平滑 "的机制，以在apex中减少后坐力，据我所知，没有因为使用ghub而被禁止的案例。 但它不能在进行臀部射击帮助你，也不能帮助你进行Hemlok自动射击，所以我在大多数情况下更喜欢使用autohotkey。 我不认为瞄准器是个好主意，它改变了你的射击习惯，所以你无法适应其他射击游戏，只要在apex使用减少后坐力就可以减少你的训练时间XD
> 
> 我试了一下，ghub驱动里报错。attempt to call a nil value Line Number:1

我错过了第一行代码，现在已经编辑到前面的回复中了
