### ISSUE TITLE
脚本运行错误

### ISSUE THREAD

**Issue by lenchen01** [mgsweet/Apex-NoRecoil-2021#114]
[https://imgtu.com/i/XCuqBt](url) 
[https://imgtu.com/i/XCKngJ](url)
请问这种情况怎么搞?完全按照过程来的,但是py脚本运行了也没弹出界面

**Comment by mgsweet** [comment]
send me your `src/`

**Comment by lenchen01** [comment]
AHK升级到最新版本之后可以用了,感谢作者

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Aaron ***@***.***>
发送时间: 2022年6月19日 12:23
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [mgsweet/Apex-NoRecoil-2021] 脚本运行错误 (Issue #114)


send me your src/

―

**Comment by zhouyingchen** [comment]
老哥问下 这个是只有压枪功能吗？没有自动锁敌是吗
