### ISSUE TITLE
Docs for stuff inside debug folder

### ISSUE THREAD

**Issue by alexonpeace** [mgsweet/Apex-NoRecoil-2021#115]
Hi
I tried running some stuff inside debug folder and I can't seem to understand what they do
but the gold_optics_assist is really cool and works awesome
it would be nice if there were some documentation for these files and what they do

**Comment by BamaBinBombin** [comment]
I was originally looking for a mouse 'shaker'...   is this what the gold_optics_assist is?  I looked at the code and really am not sure what it does, even tried it out, but still confused. 
Could you please explain what this actually does?
Thanks a lot!

**Comment by mgsweet** [comment]
![image](https://user-images.githubusercontent.com/15327389/174465713-9775fa64-c180-475a-b30e-d08a67e02559.png)
