### ISSUE TITLE
Need linux support

### ISSUE THREAD

**Issue by flytpath** [mgsweet/Apex-NoRecoil-2021#117]
as i mentioned in the title could you make this work with Linux or at least the python version 
right now it looks like it requires pywin32 to run which obviously won't work on Linux 
could you make a workaround for this and make in run on Linux
thanks

**Comment by BamaBinBombin** [comment]
you are asking for a considerably big job to be done in doing so...  I
think you better offer some serious starbucks gift cards for the motivation
needed!!!

**Comment by krampus-nuggets** [comment]
I don't see porting the program to Linux as being that much of challenge. However, setting up Linux, Steam and Apex is an annoying long process. It's an interesting challenge that I might undertake. I would not get your hopes up on me getting to this anytime soon.
