### ISSUE TITLE
Updated season 14

### ISSUE THREAD

**Issue by hitch3ns** [mgsweet/Apex-NoRecoil-2021#120]
Hi @mgsweet 

i know you are might be busy so i updated and tested the weapons based on their new colors/type new distribution, you may update as current if you or someone tested it , it was easy to understand the code logic so it was simple copy/paste around , still all thanks to your effort
PS: below detection buttons is Xbutton1 & Xbutton2 that's my side mouse buttons just let you aware of that

https://github.com/mgsweet/Apex-NoRecoil-2021/compare/main...hitch3ns:Apex-NoRecoil-2021:patch-1

**Comment by prokiller1199** [comment]
You should remove spitfire from heavy weapon in your code.

The coordinates of recoil may require update since all SMG remove barrel stabilizers and spitfire increase its recoil.

**Comment by NotMatter60** [comment]
@hitch3ns is this everything update for s14  , Thank you for the changes

**Comment by hitch3ns** [comment]
it didn't actually pattern wise have any recoil difference i tested in fire range was acceptable , and you right about spitfire although it didn't make any different it will be just kind of a clean up @prokiller1199

**Comment by hitch3ns** [comment]
@NotMatter60 ya added volt to energy, spitty to light G7 to light and ramp to carepackage those are main stuff

**Comment by AllMightyyyy** [comment]
it's not working for some reason , it just doesn't detect the weapons even after changing the keybinds or trying ur own settings it didn t work

**Comment by AllMightyyyy** [comment]
okay i managed to fix it , it would be very cool if you uploaded the edited file directly to get credit for it and make it easy for people , Nice work @hitch3ns

**Comment by hitch3ns** [comment]
@AllMightyyyy i didn't know how i just wanted ppl get 1st day update :D and its @mgsweet work anyways i just did some copy/paste around

**Comment by hitch3ns** [comment]
> You should remove spitfire from heavy weapon in your code.
> 
> The coordinates of recoil may require update since all SMG remove barrel stabilizers and spitfire increase its recoil.

i cleaned it and updated is link for  better visibility

**Comment by mgsweet** [comment]
I have merged @jayking999 's PR and will make a release later.

**Comment by NotMatter60** [comment]
@mgsweet could you do it as soon as possible bcs i need the changes thank you for this code 👍
