### ISSUE TITLE
ahk_resolution_rough_generator

### ISSUE THREAD

**Issue by FinderProcess** [mgsweet/Apex-NoRecoil-2021#123]
"ahk_resolution_rough_generator" Dosent work for me i put in the "Widht" than the "Height" after that is crashes.

**Comment by mgsweet** [comment]
Could u provide some more details like debug log or panic info?

**Comment by FinderProcess** [comment]
> Could u provide some more details like debug log or panic info?

Sorry my fault didn't know i have to open it through CMD!
