### ISSUE TITLE
Will there be future updates to Python?

### ISSUE THREAD

**Issue by YuATools** [mgsweet/Apex-NoRecoil-2021#124]
Currently Python seems to be outdated.
I am waiting for it to be updated.

**Comment by YuATools** [comment]
Thanks for the answer, @krampus-nuggets 

I have tried using this script on Win10 Pro 21H2 and it does not recoil control.
I think the content of the script is very stylish and great, but I was not convinced that it does not work.

Maybe my environment is bad, so please let me know if there is a way to improve it.

P.S.
The recoil_patterns.py is broken into about 3 lines per weapon, is there a reason for this?
When I create my own recoil pattern, will it work if I write everything on one line?

Translated with www.DeepL.com/Translator (free version)

**Comment by krampus-nuggets** [comment]
@YuATools - You can find my latest updates here on the development branch:

* [https://github.com/mgsweet/Apex-NoRecoil-2021/tree/development/python/improvements](DEV)

I'll send in a PR for merge to master when I've finished with all the updates. In that branch you'll find an updated version of the python build that I tested myself.

**NOTE** - The **.exe** build for Python is still outdated so you'll have to run it from the **main.py** file.

**VIDEO** - [Testing Update](https://res.cloudinary.com/wemakeart/video/upload/v1660250259/apex-no-recoil/11-08-2022-apex-no-recoil-update_hfmupn.mp4)

**SCREENSHOT** - [What you should see in terminal](https://res.cloudinary.com/wemakeart/image/upload/v1660250844/apex-no-recoil/apex-settings_ips7ed.png)

**Updates in DEV branch:**

* Automatic scaling to all resolutions
* Removal of pywin32 package & inclusion of native mouse-button state check
* Code clean-up and minor refactoring

**Comment by YuATools** [comment]
> @YuATools - You can find my latest updates here on the development branch:
> 
> * [https://github.com/mgsweet/Apex-NoRecoil-2021/tree/development/python/improvements](DEV)
> 
> I'll send in a PR for merge to master when I've finished with all the updates. In that branch you'll find an updated version of the python build that I tested myself.
> 
> **NOTE** - The **.exe** build for Python is still outdated so you'll have to run it from the **main.py** file.
> 
> **VIDEO** - [Testing Update](https://res.cloudinary.com/wemakeart/video/upload/v1660250259/apex-no-recoil/11-08-2022-apex-no-recoil-update_hfmupn.mp4)
> 
> **SCREENSHOT** - [What you should see in terminal](https://res.cloudinary.com/wemakeart/image/upload/v1660250844/apex-no-recoil/apex-settings_ips7ed.png)
> 
> **Updates in DEV branch:**
> 
> * Automatic scaling to all resolutions
> * Removal of pywin32 package & inclusion of native mouse-button state check
> * Code clean-up and minor refactoring

nice update
I will give this a try.
Thank you.

I'll add any issues ASAP.

**Comment by krampus-nuggets** [comment]
> > @YuATools - You can find my latest updates here on the development branch:
> > 
> > * [https://github.com/mgsweet/Apex-NoRecoil-2021/tree/development/python/improvements](DEV)
> > 
> > I'll send in a PR for merge to master when I've finished with all the updates. In that branch you'll find an updated version of the python build that I tested myself.
> > 
> > **NOTE** - The **.exe** build for Python is still outdated so you'll have to run it from the **main.py** file.
> > 
> > **VIDEO** - [Testing Update](https://res.cloudinary.com/wemakeart/video/upload/v1660250259/apex-no-recoil/11-08-2022-apex-no-recoil-update_hfmupn.mp4)
> > 
> > **SCREENSHOT** - [What you should see in terminal](https://res.cloudinary.com/wemakeart/image/upload/v1660250844/apex-no-recoil/apex-settings_ips7ed.png)
> > 
> > **Updates in DEV branch:**
> > 
> > * Automatic scaling to all resolutions
> > * Removal of pywin32 package & inclusion of native mouse-button state check
> > * Code clean-up and minor refactoring
> 
> nice update
> I will give this a try.
> Thank you.
> 
> I'll add any issues ASAP.
> 
> P.S.
> I am trying to support Japanese, can I implement it by just adding the Japanese option to Tesseract in `main.py` and setting the weapon name in `recoil_pattern.py` to Japanese?

This should work, if it doesn't you might have to troubleshoot:

1. You could try increasing the scan size in the config YAML file.
2. I'd also suggest testing the Tessract results to make sure the correct values are returned.

**Comment by ImYuxuanLi** [comment]
Hey, thank you for your work. Well I find that the python script do not work well. It did run and was able to detect what the weapon is. And it do move downwards my mouse cursor. However, its move do not help make bullets shot at one point. Did I miss something to do or set? Or do I have to use tracker tool to get weapon patterns myself?
