### ISSUE TITLE
R301 & Spitfire not working

### ISSUE THREAD

**Issue by ekstazas** [mgsweet/Apex-NoRecoil-2021#128]
For some reason, for this script and a few others, the R301 never seems to work (& spitfire with mgsweet's script).

Resolution: 1680x1050

Any fix?

**Comment by mgsweet** [comment]
The spitfire's recoil has been changed in S14. Obviously, we haven't updated the recoil pattern yet...

**Comment by mgsweet** [comment]
see: https://github.com/mgsweet/Apex-NoRecoil-2021/issues/125
