### ISSUE TITLE
Getting a trojan warning when trying to download.

### ISSUE THREAD

**Issue by jefe112** [mgsweet/Apex-NoRecoil-2021#13]
Getting a trojan warning when trying to download.

**Comment by Lobfly** [comment]
Don't worry bro,the AutoHotkey is safe and the source code is all in apexmaster.ahk

**Comment by filen1** [comment]
@jefe112 
It's probably the ahkhider.ahk and maybe ahkhider.exe. They're both safe. ahkhider needs to inject(this sends off virus alarms) so it can hide your ahk in processes. You're free to just download the apexmaster.ahk and use that but you'll likely receive a ban with no hider.

**Comment by mgsweet** [comment]
@jefe112 If you don't trust me. You can compile them yourself XD.
