### ISSUE TITLE
关于在14赛季2K分辨率下的问题

### ISSUE THREAD

**Issue by lyleaf-81** [mgsweet/Apex-NoRecoil-2021#132]
你好老哥，我一直用你登脚本，我拉取了最新的代码，用的ahk版本，发现能量枪没有任何问题，但是其他全自动都会在10发子弹后往上飘，然后再稳定准星。之前的版本没这个问题

**Comment by mgsweet** [comment]
Are u using one of the released versions? Which version are u using?

**Comment by mgsweet** [comment]
no enough details
