### ISSUE TITLE
Experiencing severe performance degradation when using new features

### ISSUE THREAD

**Issue by fatinghenji** [mgsweet/Apex-NoRecoil-2021#133]
- Version being used: Source version
- Features enabled: `auto_fire`, `fast_pk`, `gold_optics`
- Computer hardware:
 - CPU: Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz 2.50 GHz
 -GPU: NVIDIA 1050 (mobile version)
 -Memory: 8G
-Problems encountered: After enabling `fast_pk` and `gold_optics`, I encountered serious performance problems, the frame rate of my game fluctuated from around 60 fps to less than 30 fps

**Comment by mgsweet** [comment]
Can't reproduce. try v1.3.4 to see if the problem still exists pls.
