### ISSUE TITLE
Why check 2 weapon slots?

### ISSUE THREAD

**Issue by barbaduk** [mgsweet/Apex-NoRecoil-2021#135]
Why do we check 2 different spots to get the weapon slot (this info isn't used anywhere)? You can get current ammo type by checking one of _this_ points:
![ScreenX_2022 08 25](https://user-images.githubusercontent.com/41954202/186704204-848bf9a8-5dfc-4d96-aadb-119bb54b43a2.png)
Haven't find any situation when any of this spots are covered (but maybe it does, i don't have every Legend to test it...)

**Comment by mgsweet** [comment]
1. yes, I agree that to detect color, your idea looks better.
2. I didn't think that much when I write down those codes. But if I need to change them, I have to also change all those resolution config files, which would be a disaster.
3. For feature like the peacekeeper fast reload, I may need to know which weapon is now activated.
