### ISSUE TITLE
I want to develop a resource management assist.

### ISSUE THREAD

**Issue by NotesRabbit** [mgsweet/Apex-NoRecoil-2021#138]
Hello, seniors
I would like to develop an apex resource management helper
I am now learning your source code
I will encounter some questions, I do not know that the senior you can help me?
你好，前辈
我想开发一个apex资源管理辅助
我现在正在学习你的源码
我会遇到一些疑问，不知道前辈你能进行帮助吗？
1.Senior, what is hyde.dll?When did it use it?
前辈，hyde.dll是什么东西？什么时候使用了它？
2.Is it possible for AHK to prevent EA detection and use USB communication camouflage?
ahk防止ea检测，使用usb通信伪装，这样可行吗？

**Comment by escape0707** [comment]
hyde.dll is to prevent EA from detecting the AHK program.

Which language do you prefer?

**Comment by mgsweet** [comment]
In fact, I have no research on anti-detection. That part is all code from others. please Google it yourself.
