### ISSUE TITLE
Prowler and Hemlock's shooting is blocked no matter auto shot is on or not.

### ISSUE THREAD

**Issue by escape0707** [mgsweet/Apex-NoRecoil-2021#140]
No matter if you use the auto shooting option or change the script to make them `is_single_weapon := false`, if you shoot those weapons, hold left mouse button for a while, release when all those first rounds are shooted, then left click, the next rounds can't be shooted.

I'm going to take a look at the flaws of the source code.

BTW, it's probable a bad idea to make Prowler, Hemlock, 30-30 and G7 Scout to auto-shoot. Auto-shoot works best with weapons like P2020 and Hemlock single mode, which is in single shooting mode but has a high and steady shooting rate.

**Comment by escape0707** [comment]
Guess it's because the second click comes during the sleep phase in Loop. Gotta try fixing it out.

**Comment by mgsweet** [comment]
I think it has been fixed in v1.3.4. Could u pls try again?

**Comment by mgsweet** [comment]
Remove 3030, G7 already
