### ISSUE TITLE
P2020 auto doesn't work

### ISSUE THREAD

**Issue by kakahost** [mgsweet/Apex-NoRecoil-2021#141]
When i choose P2020, it foesn't work. And how must work PeaceMaker fast load? I can do it by my own hands, but this thing doesn't work. Also, what gold scope mode does?

**Comment by escape0707** [comment]
Please use your mother tongue because your English is currently unable to decipher.

**Comment by escape0707** [comment]
Then just start a pull request to make it available for users at other resolution. You are welcomed.

**Comment by mgsweet** [comment]
> Well just say why pk_fastload is available only for 2k? 1k users want it too

Because I personally use 2k res.
As u know, the bug has been fixed. The ROI to support multi-res is very low.
