### ISSUE TITLE
hyde.dll is deteced as a trojan

### ISSUE THREAD

**Issue by CodingGuy32** [mgsweet/Apex-NoRecoil-2021#142]
My anti virus detects the hyde.dll as a trojan

**Comment by chenzijian0** [comment]
Of course.
hede.dll is used to hide the process from being scanned by the system.
A normal program doesn't try to hide itself so the antivirus will recognize it as a trojan

**Comment by CodingGuy32** [comment]
That's odd because the one from unknowncheats does the same but doesn't get
detected
