### ISSUE TITLE
金镜功能不工作

### ISSUE THREAD

**Issue by GITDK2022** [mgsweet/Apex-NoRecoil-2021#144]
大佬，我试了最新版本，其他功能都正常，金镜功能勾选了但是不工作，我也试着按0开启/关闭，依然没有任何效果，我用的是简体中文版的游戏，我需要检查哪些方面？

**Comment by escape0707** [comment]
What's your game resolution?

**Comment by GITDK2022** [comment]
2560x1440  and 1920x1080

**Comment by escape0707** [comment]
As per

https://github.com/mgsweet/Apex-NoRecoil-2021/blob/60a9f65c1bbda9e38786c5c3bf4ed2cd20acb65e/AHK/src/apexmaster.ahk#L230

and

https://github.com/mgsweet/Apex-NoRecoil-2021/blob/60a9f65c1bbda9e38786c5c3bf4ed2cd20acb65e/AHK/src/apexmaster.ahk#L407

You'll need to press <kbd>0</kbd> to toggle it on. Have you tried that?

This script still needs some overhaul, for sure.

**Comment by mgsweet** [comment]
try the latest -- v1.3.4. There were some bugs before.
