### ISSUE TITLE
i use 1366x768

### ISSUE THREAD

**Issue by soullex09** [mgsweet/Apex-NoRecoil-2021#145]
the secondary weapon doesnt have recoil only the primary weapon however when i use other resolution both works only in 1366x768 reso had an issue, i use 1366x768 because thats my monitor max resolution it wont go any higher reso

**Comment by mgsweet** [comment]
will take a look at the next version

**Comment by mgsweet** [comment]
Or maybe you can help me fix that.

**Comment by skillHao** [comment]
我也有一个一样的问题，我在1920*1080分辨率下只能使用R301和CAR（无法使用Flatline和r99），但是在1600*900的分辨率下Flatline和r99可以使用了，但是r301和CAR又不能NoRecoil
了

**Comment by skillHao** [comment]
I also have the same problem, I can only use R301 and CAR at 19201080 resolution (Flatline and R99 cannot be used), but Flatline and R99 can be used at 1600900 resolution, but R301 and CAR cannot be NoRecoil the

**Comment by mgsweet** [comment]
Just did a quick check. The script works on both weapons in 1366*768 on my PC.
