### ISSUE TITLE
Have anyone getting banned by using this?

### ISSUE THREAD

**Issue by kevn9042** [mgsweet/Apex-NoRecoil-2021#146]

**Comment by Traumeri** [comment]
I have been using it for 2 weeks now and no I haven't been banned yet but I would like for the owner to increase the safety if possible

**Comment by NNanfeng** [comment]
I have been using it for 6 months now and no I haven't been banned yet but I would like for the owner to increase the safety if possible

**Comment by mgsweet** [comment]
https://github.com/mgsweet/Apex-NoRecoil-2021/issues/72
