### ISSUE TITLE
新版本金镜功能仍然无法使用

### ISSUE THREAD

**Issue by jake936** [mgsweet/Apex-NoRecoil-2021#149]
分辨率1920×1080无边框，勾选金镜功能后进游戏仍然无法使用

**Comment by jake936** [comment]
是由于fov的问题吗？

**Comment by mgsweet** [comment]
确实有点问题，看看v1.3.5

**Comment by fatinghenji** [comment]
> 确实有点问题，看看v1.3.5

问题依旧存在，使用版本是：[5821895](https://github.com/mgsweet/Apex-NoRecoil-2021/commit/58218956b3d9aec7ed170677d2f9a41668e1f12a)

**Comment by SLWXA** [comment]
这个金镜是什么效果，有人能告诉我下吗

**Comment by mgsweet** [comment]
你有试过开枪不，在你捡到金镜后按0开启，然后尝试瞄着开枪就好了
