### ISSUE TITLE
lstar枪线远距离很飘
转换者冲锋枪枪线上飘

### ISSUE THREAD

**Issue by jake936** [mgsweet/Apex-NoRecoil-2021#151]

**Comment by fatinghenji** [comment]
相同问题，转换者冲锋枪在腰射时出现后坐力补充不足的问题

**Comment by mgsweet** [comment]
Their pattern is ... not bad. Since I seldom use them, I have no motivation to update their pattern. Maybe you can make one and create a pull request.
