### ISSUE TITLE
Noticed issues with 3 guns when testing auto-fire:

### ISSUE THREAD

**Issue by combataran** [mgsweet/Apex-NoRecoil-2021#153]
Autofire on P2020 works during hipfire and ADS.

Wingman: Does not autofire in ADS/hipfire, pulls down when left click is held down in both ADS/hipfire
Scout: Does not autofire in hipfire/ADS
30-30: Does not autofire in hipfire/ADS

Using v135, here are my settings:

[screen settings]
resolution="1920x1080"

[mouse settings]
sens="1.5"
zoom_sens="1.0"
auto_fire="1"
ads_only="0"
[voice settings]
volume="80"
rate="7"
[other settings]
debug="0"
gold_optics="0"
fast_pk="0"

**Comment by jayking999** [comment]
Please keep zooming 100

**Comment by mgsweet** [comment]
wingman, scout, 3030 has been removed from the autofire weapon list. The experience was shit...So I removed them
