### ISSUE TITLE
AHK Version Controller support

### ISSUE THREAD

**Issue by Corehexagon** [mgsweet/Apex-NoRecoil-2021#155]
Is there a way to add controller support on pc  or can some body tell me how to edit the keys in the script because in the pc version even if you change the default keys then the script doesn't work. I maybe be able to edit the script myself if I'll be provided with the info 

Thanks in advance !

**Comment by mgsweet** [comment]
For how to edit the keys, take a look at：
- https://www.autohotkey.com/docs/Hotkeys.htm
- https://www.autohotkey.com/docs/KeyList.htm

For Controller support, the answer is no. AHK does not support joystick button input simulation. In their document, they said a joystick emulator such as vJoy may help. But I doubt that using a joystick emulator can still let u keep the aim assist feature.
