### ISSUE TITLE
关于贴吧所说ahk大范围拉闸的情况

### ISSUE THREAD

**Issue by HTTama** [mgsweet/Apex-NoRecoil-2021#157]
注意到应该是某个淘宝店铺修改再出售的版本，是因为他们的版本固定使用同一个uuid吗？现在的1.3.5是否安全

**Comment by fatinghenji** [comment]
不清楚，先观望，今晚观望下 banwave

**Comment by kazuhalfsugar** [comment]
我仍在同一个账户中使用release1.2.6的版本和uuid生成器，因为我对新版本的gui.exe文件感到不安（实际上ahk和exe对于反作弊或许没有区别，我尊重作者的成果）。我自己修改了部分代码包括S14赛季的武器更新内容，从今年3月到现在没有被封禁的情况。
顺带一提，我修改了havoc和devotion的后座图案让他们工作地更好，目前的图案会过度向下，反而你需要抬起瞄准，这种反直觉的操作方式对瞄准困难。
如果你有被封禁的顾虑，可以使用Logitec GHub的抖动射击。它是绝对安全的，只是在使用部分武器（如bocek和havok）时不自然的抖动会展现给你的观战球员。

**Comment by HTTama** [comment]
> 我的同一个账簿中的版本和 1.2.6 的版本没有新的释放生成，因为我对版本的 gui.exe 文件不放心（其实对于作者的反作弊可能有什么不同，我很喜欢的成果）。我自己修改了 S14封盖武器的部分内容，从一月到没有被禁的更新情况。会过度瞄准，你需要瞄准以瞄准的方式，锁定不同的困难。 你有被禁止使用的部分安全日志的潜在范围，完全可以在使用（如bocek和havo会）时不自然的给你的观战。

过度下压可能和游戏内平滑移动减少后座力机制有关，我一般会让ahk设定灵敏度高于游戏内灵敏度，这样在移动/跟枪射击和观战场景都会体现出更自然的下压

**Comment by HTTama** [comment]
> > 我仍在同一个账户中使用release1.2.6的版本和uuid生成器，因为我对新版本的gui.exe文件感到不安（实际上ahk和exe对于反作弊或许没有区别，我尊重作者的成果）。我自己修改了部分代码包括S14赛季的武器更新内容，从今年3月到现在没有被封禁的情况。 顺带一提，我修改了havoc和devotion的后座图案让他们工作地更好，目前的图案会过度向下，反而你需要抬起瞄准，这种反直觉的操作方式对瞄准困难。 如果你有被封禁的顾虑，可以使用Logitec GHub的抖动射击。它是绝对安全的，只是在使用部分武器（如bocek和havok）时不自然的抖动会展现给你的观战球员。
> 
> 你能分享你这两把枪的txt文件吗？我也发现这两把枪下拉严重，如果调灵敏度，其余的枪又压不住了

只是使用了默认的文件配置。在使用ahk辅助之前我对自己在一定距离内的控枪也有信心，所以使用高于游戏内的灵敏度设置让我的控枪看起来更自然，使用ahk只是为了增加我的交战半径，以及让我在中近距离更专注于跟枪

**Comment by kazuhalfsugar** [comment]
> 你能分享你这两把枪的txt文件吗？我也发现这两把枪下拉严重，如果调灵敏度，其余的枪又压不住了

**建议在覆盖前备份你的图案，因为我不能保证它适合你的分辨率和灵敏度**
我减少了Devotion的前段后座补偿，让它更符合这把武器原来的情况（大多数玩家无法控制前几件弹药的跳动，ahk的表现是不自然的）
我对枪械后坐力图案坐标还原不是很了解，所以只是在原本的图案上细小调整
[Devotion.txt](https://github.com/mgsweet/Apex-NoRecoil-2021/files/9616114/Devotion.txt)
[DevotionTurbo.txt](https://github.com/mgsweet/Apex-NoRecoil-2021/files/9616116/DevotionTurbo.txt)
[Havoc.txt](https://github.com/mgsweet/Apex-NoRecoil-2021/files/9616117/Havoc.txt)
[HavocTurbo.txt](https://github.com/mgsweet/Apex-NoRecoil-2021/files/9616118/HavocTurbo.txt)
havoc在射击时屏幕抖动很大，我不清楚是图案中的射击间隔过小还是它本来如此。大多数时候我偏爱平行线

**Comment by GITDK2022** [comment]
> > 你能分享你这两把枪的txt文件吗？我也发现这两把枪下拉严重，如果调灵敏度，其余的枪又压不住了
> 
> **建议在覆盖前备份你的图案，因为我不能保证它适合你的分辨率和灵敏度** 我减少了Devotion的前段后座补偿，让它更符合这把武器原来的情况（大多数玩家无法控制前几件弹药的跳动，ahk的表现是不自然的） 我对枪械后坐力图案坐标还原不是很了解，所以只是在原本的图案上细小调整 [Devotion.txt](https://github.com/mgsweet/Apex-NoRecoil-2021/files/9616114/Devotion.txt) [DevotionTurbo.txt](https://github.com/mgsweet/Apex-NoRecoil-2021/files/9616116/DevotionTurbo.txt) [Havoc.txt](https://github.com/mgsweet/Apex-NoRecoil-2021/files/9616117/Havoc.txt) [HavocTurbo.txt](https://github.com/mgsweet/Apex-NoRecoil-2021/files/9616118/HavocTurbo.txt) havoc在射击时屏幕抖动很大，我不清楚是图案中的射击间隔过小还是它本来如此。大多数时候我偏爱平行线

谢谢

**Comment by mgsweet** [comment]
I don't really like this kind of question. You can easily get your answer with your test account. If you want to know how to run the script safely, take a look here: https://github.com/mgsweet/Apex-NoRecoil-2021/issues/72. Also, if the script really has some problems, people would complain about it here: https://www.unknowncheats.me/forum/apex-legends/476508-apex-norecoil-2021-official-post-auto-detect-multiple-resolution-supported.html. I am not responsible for the version sold by Taobao. I doubt whether they have followed the [GPL-3.0 license](https://github.com/mgsweet/Apex-NoRecoil-2021/blob/main/LICENSE) agreement. It seems that they have not given the source code.
