### ISSUE TITLE
和平捍卫者会在手里不停地鬼畜

### ISSUE THREAD

**Issue by xyxywan** [mgsweet/Apex-NoRecoil-2021#158]
和平捍卫者，当你打了一发子弹出去，就会在你手里像撸管一样来回鬼畜....直接人傻了

**Comment by mgsweet** [comment]
v1.3.5?

**Comment by mgsweet** [comment]
From v1.3.5, the peacekeeper-fast-reload feature has been removed since the bug has been fixed.

**Comment by yizhongrenya** [comment]
> 从 v1.3.5 开始，维和人员快速重装功能已被删除，因为该 bug 已得到修复。
猎兽冲锋枪和G7侦察枪无法使用auto_fire
