### ISSUE TITLE
猎兽的连击有问题，直接卡死了

### ISSUE THREAD

**Issue by sjiebn** [mgsweet/Apex-NoRecoil-2021#162]

**Comment by sjiebn** [comment]
一直在压枪但是没有射击

**Comment by baoc2** [comment]
在`else if (CheckWeapon(PROWLER_PIXELS)) {`
下面加一行`is_single_fire_weapon := true`
不知道为啥这行没了所以被识别为一般武器就无法正常连击

**Comment by mgsweet** [comment]
Fixed in v1.3.6
