### ISSUE TITLE
New Version 1.3.6 bannable?

### ISSUE THREAD

**Issue by saberana** [mgsweet/Apex-NoRecoil-2021#165]
Hello. Yesterday I downloaded a new version of the script 1.3.6. Set up, run everything correctly as it should be. Then I went to the firing range for a test. After shooting a little bit with r301, and then with r99 from ironsights. The game said that the server crashed. And then I also could not go to public servers in trios. Usually it means ban. I shet in my pants, immediately logged out of the game, and immediately used spoofer to erase all data and change the HWID. After Rebooting the computer, fortunately everything worked out and I'm not banned. Can you check bans for script or not on empty account. Also, goldopt and fastpk were enabled in the settings, but I did not use them at all as mentioned above. Launched through apexmaster.ahk as admin, after using uuid_generator.

**Comment by BamaBinBombin** [comment]
Test it out yourself.  Why you have to bother the programmer to do
more testing that you could easily do yourself!?  You want someone to feed
you while you play also... jk!!!

**Comment by saberana** [comment]
> 

I'm testing bro, but it may happen like last year when there was a wave of bans, who used the script. Author should key an eye for that.

**Comment by kazuhalfsugar** [comment]
Safe and sound with uuid generator and ahk.

**Comment by mgsweet** [comment]
No
