### ISSUE TITLE
About ammo detection

### ISSUE THREAD

**Issue by BlueCat-Frisk** [mgsweet/Apex-NoRecoil-2021#167]
i found this script has no `ammo detection`
I tried ammo detection in 1920x1200 resolution, It should be available
Check whether the number of ammo is 0 by three points of the number 0
`
IsNoAmmo()
{
    PixelGetColor, check_ammo_color_1, 1760, 1100
    PixelGetColor, check_ammo_color_2, 1775, 1095
    PixelGetColor, check_ammo_color_3, 1774, 1105
    return check_ammo_color_1 == 0xFFFFFF && check_ammo_color_2 == 0xFFFFFF && check_ammo_color_3 == 0xFFFFFF
}
`
But there maybe a problem when the number of ammo is 10
Because I didn't check the second digit of ammo :)

This is the approximate location of the checkpoint
<img width="22" alt="Image" src="https://user-images.githubusercontent.com/100213430/192754849-e95b1797-87ff-4e58-97b8-ac696ceedb85.png">

**Comment by mgsweet** [comment]
Good idea. But it needs too much work to support all resolutions. No plan to add it.

**Comment by BlueCat-Frisk** [comment]
Actually, just check the checkpoint in the lower right corner :)
