### ISSUE TITLE
Add the option to choose which guns it activates on

### ISSUE THREAD

**Issue by Senixisded** [mgsweet/Apex-NoRecoil-2021#169]
I'm pretty bad at AHK and I don't wanna break your masterpiece ( knowing myself I can easily fck something up ) but I wanted to suggest a system where we can choose which guns the script activates on the gui and it would save in it in the settings.ini file

## For example :
I'm pretty bad with the Flatline, so I want it to activate on the Flatline, but I'm a god with the R99 so I don't want it to activate on the R99.
I was hoping this could be added as a quality of life feature but I don't know how difficult that would be.
Thank you for reading!

**Comment by CHN1029** [comment]
> I'm pretty bad at AHK and I don't wanna break your masterpiece ( knowing myself I can easily fck something up ) but I wanted to suggest a system where we can choose which guns the script activates on the gui and it would save in it in the settings.ini file
> 
> ## For example :
> I'm pretty bad with the Flatline, so I want it to activate on the Flatline, but I'm a god with the R99 so I don't want it to activate on the R99. I was hoping this could be added as a quality of life feature but I don't know how difficult that would be. Thank you for reading!

You can enter the resolution folder, find the corresponding resolution ini file, and add ";" to the name of the corresponding gun Symbols, such as:; R99, so the identification of the gun will be invalid.

**Comment by mgsweet** [comment]
@CHN1029 good answer.
