### ISSUE TITLE
Resolution: 2560x1080 - Recoil Control doesn't work

### ISSUE THREAD

**Issue by xXKTMasterXx** [mgsweet/Apex-NoRecoil-2021#170]
I replaced the custom resolution template with my own (2560x1080) but the recoil control doesn't work. I also tried changing my pc resolution to 1920x1080 to test it with the pre made setting (1920x1080) and it worked. Does this script just not work with 2560x1080 in general or did I do something wrong?

![2022-10-08_02h19_25](https://user-images.githubusercontent.com/46991728/194678072-40604eb7-e231-42c4-b2e0-6d66fc8b1d6b.png)
![2022-10-08_02h20_27](https://user-images.githubusercontent.com/46991728/194678069-51ff2190-4f2b-46be-944f-994abe9f9242.png)
![2022-10-08_02h21_28](https://user-images.githubusercontent.com/46991728/194678066-b76499cc-4bbe-4315-afec-399a753b1339.png)

**Comment by yizhongrenya** [comment]
专注轻机枪和转换者冲锋枪效果很差，怎么解决，求帮助

**Comment by xXKTMasterXx** [comment]
> 专注轻机枪和转换者冲锋枪效果很差，怎么解决，求帮助

I've tested the r301 on 1920x1080 resolution (pc scaling) and it worked good, no recoil. When I tried it with 2560x1080 (my actual resolution) the recoil on the r301 was still there, no difference.

**Comment by xXKTMasterXx** [comment]
I used pmeter to set new values and the r99 actaully worked but all other guns didn't

**Comment by xXKTMasterXx** [comment]
I fixed it, went in and changed the gun 1 and gun 2 pixel positions and the guns I use and it worked again

**Comment by mgsweet** [comment]
Maybe you can share your work. Many people are asking for 2560x1080 as I notice.

**Comment by mgsweet** [comment]
Actually, you can just replace all the stuff in `customized.ini` and choose the **customized** resolution option in GUI instead of changing the code.

**Comment by xXKTMasterXx** [comment]
> Maybe you can share your work. Many people are asking for 2560x1080 as I notice.

These are the pixel coordiantes for the weapon 1 and 2 and the guns r99, r301, flatline, car and volt.
I also noticed that the volt recoil pattern isn't "that" accurate because it pulls to the right at the end.

**Coordiantes:**
weapon1 = "2160,1040"
weapon2 = "2460,1040"
r99 = "2223,978,1,2217,978,0,2305,989,1"
r301 = "2216,970,1,2216,975,0,2311,985,1"
flatline = "2210,975,1,2210,979,0,2306,993,1"
volt = "2225,975,1,2225,980,0,2277,997,1"
car = "2234,994,1,2237,994,0,2300,992,1"

**Comment by EjazEkay** [comment]
Icon™#5392 if you still need help add me to discord will help you

**Comment by mgsweet** [comment]
see: https://github.com/mgsweet/Apex-NoRecoil-2021/issues/127
