### ISSUE TITLE
ads_only 

### ISSUE THREAD

**Issue by EjazEkay** [mgsweet/Apex-NoRecoil-2021#175]
ads_only isnt working on any screen resolution and i have searched alot to fix it but i am unable to fix it if anybody know how to fix it or can help me please help me to fix ads_only script issue thanks

**Comment by qsirwyk** [comment]
Do you know what ads_only is for? I don't understand it

**Comment by EjazEkay** [comment]
ads_only is when you aim then the script work and when you don't aim it won't work and

**Comment by qsirwyk** [comment]
Thank you very much, although that is very good, but I think it is a little difficult to achieve through this script, if you can identify the translucent ultimate skill charging state, maybe it can be achieved, maybe need to change the idea 

By the way, do you know what kind of weapon sella_weapon is?

**Comment by EjazEkay** [comment]
Yes I am playing with ads_only and it make me professional because without
ads_only when you shoot on enemy without ads the script make your aim worst
I dont know the sella weapon i think thats mean like default or i am not
sure

**Comment by Kazemiro** [comment]
@qsirwyk @EjazEkay 
Sella is Rampart’s Sheila (Ultimate)

**Comment by qsirwyk** [comment]
@Kazemiro Hahaha So that's it!
Thank you very much!

**Comment by Kazemiro** [comment]
@qsirwyk np :)
