### ISSUE TITLE
Alt-Tabs Randomly

### ISSUE THREAD

**Issue by Karuneko** [mgsweet/Apex-NoRecoil-2021#178]
In some occasions it alt-tabs out of APEX.

Already happened multiple times for me.

**Comment by QASDJKL5** [comment]
Try alt-tabs out of the game, see what it does, its not a bug of the software.

**Comment by Karuneko** [comment]
> 

What do you mean by this??

It randomly alt-tabs OUT of the game sometimes in use.

**Comment by QASDJKL5** [comment]
sorry, i'm not a native english speaker. my english is not that good.
I mean alt-tab is a function of windows. by using it, you could switch between softwares.
You had other softwares on when you were playing apex, by using alt-tab, you switched to an another software window, so you were out of APEX.
If you want to avoid this, try not pushing these two buttons at the same time.

**Comment by BamaBinBombin** [comment]
If a message pop-up happens from another windows application while in
full-screen, it will change applications to the application doing the
pop-up message...  I think AHK is giving a pop-up and making apex
minimize;  I think the 0-button is maybe the cause.  It is not like someone
is actually pressing ALT+TAB to switch or minimize apex.
Removing pop-up messages from code is my guess, but again, I am not 100%
certain.

**Comment by Karuneko** [comment]
> sorry, i'm not a native english speaker. my english is not that good. I mean alt-tab is a function of windows. by using it, you could switch between softwares. You had other softwares on when you were playing apex, by using alt-tab, you switched to an another software window, so you were out of APEX. If you want to avoid this, try not pushing these two buttons at the same time.

_Your english is good. Yes it is a windows function but I am not pressing the buttons, My Alt key is for the Survival Item (Heat Shield / Mobi). Sometimes most frequently it switches to the desktop (Windows Key + D). Especially in intense fights (frequently) it will randomly put me into another software (Chrome, Spotify, i.e) without pressing both buttons (Alt+Tab and/or Windows+D)._

> If a message pop-up happens from another windows application while in full-screen, it will change applications to the application doing the pop-up message... I think AHK is giving a pop-up and making apex minimize; I think the 0-button is maybe the cause. It is not like someone is actually pressing ALT+TAB to switch or minimize apex. Removing pop-up messages from code is my guess, but again, I am not 100% certain.

_I will look into it, the only things that are open when I play is Steam and Discord, It could maybe be discord notifications but I do not hear the ping and no banner thing appears on the desktop mode where it usually switches to. It can be security notifications but still, no banner or the sound of the notification. Just in desktop randomly. I will turn off notifications all together to test._

_If it is from the code I do not know what to change nor how to make the debug sound the woman (lol), Kindly let me know in simple terms what might it be. Much Appreciated._

**Comment by BamaBinBombin** [comment]
"        Tooltip("has_gold_optics: " + has_gold_optics)"

Again, not certain, but this may be the line causing the issue.

**Comment by Kazemiro** [comment]
Yes, this should be for the gold optics debugging.
You can wrap it with
```
if (debug) {
Tooltip("has_gold_optics: " + has_gold_optics)
}
```

**Comment by Senixisded** [comment]
> 

What does this do exactly?

**Comment by Kazemiro** [comment]
@Senixisded when you press 0 on the keyboard, the fame will minimise and you will see a small message in the middle of the screen saying “has_gold_optics: 1”. This message is for debugging purpose.
@BamaBinBombin  mention that this is cause by the following line in the AHK script:

> " Tooltip("has_gold_optics: " + has_gold_optics)" Again, not certain, but this may be the line causing the issue.
> […](#)

So, the code i mentioned is to display the message only if you start the ahk with the debug option.
