### ISSUE TITLE
seek help

### ISSUE THREAD

**Issue by kong940** [mgsweet/Apex-NoRecoil-2021#181]
Why is the use of AHK ineffective after the season update?

**Comment by Kazemiro** [comment]
Works with me with no issue, just the RE45 needs an update.
Check this commit
<https://github.com/mgsweet/Apex-NoRecoil-2021/pull/180/files>
[60071012.png]
Update apexmaster.ahk by QASDJKL5 · Pull Request #180 · mgsweet/Apex-NoRecoil-2021<https://github.com/mgsweet/Apex-NoRecoil-2021/pull/180/files>
github.com<https://github.com/mgsweet/Apex-NoRecoil-2021/pull/180/files>


On 4 Nov 2022, at 11:47 pm, kong940 ***@***.***> wrote:

﻿

Why is the use of AHK ineffective after the season update?

**Comment by kong940** [comment]
Still no effect
And I've seen people who have the same problem and ask questions#182

**Comment by kong940** [comment]
> 与我一起工作没有问题，只是RE45需要更新。 检查此提交：https://github.com/mgsweet/Apex-NoRecoil-2021/pull/180/files
Still no effect
And I've seen people who have the same problem and ask questions#182
Although he wrote in Chinese, you can translate it

**Comment by mgsweet** [comment]
season 15 is now supported without any game test. have no time to play :(
