### ISSUE TITLE
黄金光学不起作用啊。

### ISSUE THREAD

**Issue by zzxqy** [mgsweet/Apex-NoRecoil-2021#182]
2560x1440
1920x1080
全屏/无边框
都试过了 按0 开火 无效
还有小帮手 3030这种枪可以设置不启用免后座吗
半自动武器用着非常奇怪
可以屏蔽掉就好了
还有专注和某把枪 压的异常奇怪
作者万岁

**Comment by kong940** [comment]
大哥，你为啥不用英文，他们又看不懂

**Comment by hooll** [comment]
> 大哥，你为啥不用英文，他们又看不懂

作者是国人

**Comment by zzxqy** [comment]
> 大哥，你为啥不用英文，他们又看不懂

草 我看作者是国人 就没用 等我重发一个
