### ISSUE TITLE
need update for season 15

### ISSUE THREAD

**Issue by Igors7999** [mgsweet/Apex-NoRecoil-2021#184]
pattern update andc are package update

**Comment by richardzzp** [comment]
+1

**Comment by Traumeri** [comment]
+1

**Comment by mgsweet** [comment]
I am on a business trip. It may take two weeks before I can go home.

**Comment by TBM1337** [comment]
> 

我想问一下，我学习了原作者的方法，用AE跟踪导出数据在转换成你用的这种格式，发现不管是转换之前还是转换之后的参数鼠标偏移都实在是太大了

**Comment by richardzzp** [comment]
> 
导出数据之后，使用“AHK\debug\make_recoil”目录下的pattern_maker.ahk制作对应的pattern即可。注意调参，主要是sen要设置好，然后cmod要慢慢调。调出合适的，可以放到src的模式文件夹下即可。
参考：https://github.com/vengefulcrop/AE-Recoil-Pattern-Generation/
https://www.unknowncheats.me/forum/apex-legends/467406-method-generating-recoil-patterns-ahk-script-development-testing.html

**Comment by mgsweet** [comment]
@richardzzp correct:)
