### ISSUE TITLE
Ahk not working

### ISSUE THREAD

**Issue by youngdeag** [mgsweet/Apex-NoRecoil-2021#185]
I have folowed every step, exactly how it's supposed to be but In game I still have normal recoil.
When I ran the debug option, It did read the guns I had in the AI voice...

So I'm not sure what's wrong....

Thanks for the help!
Regards,
Deag

**Comment by richardzzp** [comment]
也许你是右键切换开镜？
需要改成右键按住开镜

**Comment by mgsweet** [comment]
Have u tried to turn off ads_only?
