### ISSUE TITLE
python版本的可以同时接入百度的OCR识别来达到支持中文

### ISSUE THREAD

**Issue by s281542686** [mgsweet/Apex-NoRecoil-2021#187]
python版本的可以同时接入百度的OCR识别来达到支持中文，改造很简单已经实现了。
如果需要的话我可以捐献。

**Comment by davin860116** [comment]
> python版本的可以同時接入百度的OCR知識別達到支持中文，改造成很簡單已經實現了。 如果需要的話我可以提供。

想學習一下 可以交流嗎?

**Comment by krampus-nuggets** [comment]
@s281542686 - From what I can see, Baidu's OCR is mainly cloud based. Cloud based OCR will add a lot of latency, do you know if they have a binary?

**Comment by s281542686** [comment]
@davin860116 
[https://ai.baidu.com/ai-doc/OCR/Ek3h7xypm](https://ai.baidu.com/ai-doc/OCR/Ek3h7xypm)
需要注意的是，要对image 做 to_png，其他的就没什么了。照着文档里面的实例处理就行了。
image = sct.grab({
            "left": data["scan_coord_one"]["left"],
            "top": data["scan_coord_one"]["top"],
            "width": data["scan_coord_one"]["width"],
            "height": data["scan_coord_one"]["height"]
        })
 image = tools.to_png(image.rgb, image.size)
