### ISSUE TITLE
专注轻机枪不稳定，哈沃克带涡轮增压器无法压枪，可以维护更新一下吗！

### ISSUE THREAD

**Issue by yizhongrenya** [mgsweet/Apex-NoRecoil-2021#203]

**Comment by iroywang** [comment]
[DevotionTurbo.txt](https://github.com/mgsweet/Apex-NoRecoil-2021/files/10251714/DevotionTurbo.txt)
专注用这个

**Comment by yizhongrenya** [comment]
> [DevotionTurbo.txt](https://github.com/mgsweet/Apex-NoRecoil-2021/files/10251714/DevotionTurbo.txt) 专注用这个

谢谢，好了一点了，哈沃克带涡轮增压器无法压枪，这个您有解决方法吗

**Comment by Eternal-Walnut** [comment]
你的分辨率是多少？如果你是1980x1080的话 请尝试使用 #201
对于其他分辨率，我不确定是否因为我添加单发模式检查的时候让专注和哈沃克涡轮增压器位置统一时分辨率内位置填写错误

**Comment by mgsweet** [comment]
试试 v1.3.9
