### ISSUE TITLE
今天被ban了，是被检测到了吗，我使用了更换UUID

### ISSUE THREAD

**Issue by yizhongrenya** [mgsweet/Apex-NoRecoil-2021#209]

**Comment by yizhongrenya** [comment]
还是被封了，请告诉我原因，目前使用它是否还可靠

**Comment by liu19666** [comment]
你除了这个自动识别压枪，还开了其他东西吗？我这次也被封了，不过我同时使用了淘宝的便宜ai，已经确定该ai这次又又又拉闸了，所以我暂时不确定这个no-recoil有没有问题，等两天看看其他人的反馈吧。

**Comment by turaki0423** [comment]
今天7场控制号就没了 只有用这个no recoil

**Comment by mgsweet** [comment]
全部功能都开了试了一晚没有什么问题
