### ISSUE TITLE
Devotion with and without turbocharger goes nuts at the end-

### ISSUE THREAD

**Issue by 4ch00** [mgsweet/Apex-NoRecoil-2021#210]

**Comment by 4ch00** [comment]
> Bro, has your account been banned in the past few days after using this software?

No, my account has never been banned. I use the "green.ahk" and renamed it. I also have the whole script on a USB instead of my harddrive for max security, i also put my own UUID everytime i start the script. I think its pretty much undetectable that way

**Comment by BamaBinBombin** [comment]
I might be wrong, but changing the UUID every single time might be a very
big sign of something suspicious....

**Comment by mgsweet** [comment]
No plan to fix it. PR is welcome if u got a good one. You can also try to generate the pattern yourself. See https://github.com/mgsweet/Apex-NoRecoil-2021/tree/main/AHK/debug/make_recoil.
