### ISSUE TITLE
Can't be used after last update of game

### ISSUE THREAD

**Issue by Worship-man** [mgsweet/Apex-NoRecoil-2021#213]
Screen resolution 1920×1080

Everything was normal before

**Comment by ironkoo** [comment]
same but my resolution is 2560x1440

**Comment by cassame** [comment]
not working on 1600x900 and 1920x1080, they update smthing to detect ahk or what?

**Comment by Crashtest33** [comment]
Definitely not. r5apex.exe & EA can't ban for use of .ahk files. They do not edit or bypass the game files in any way. It just moves the screen so many pixels based on a mouse click. > not working on 1600x900 and 1920x1080, they update smthing to detect ahk or what?

**Comment by cassame** [comment]
It was my bad, accidentally forgot that i enable nvidia freestyle color correction, take a note
