### ISSUE TITLE
not working on 25.01.23

### ISSUE THREAD

**Issue by Nielsuuu** [mgsweet/Apex-NoRecoil-2021#219]
idk why few day earlier was working fine now i want to use it and does nothing

**Comment by ArinLP** [comment]
for me too not working and i don't know why :_(

**Comment by Nep-Timeline** [comment]
I think you should check yourself
[Whether the resolution is changed]
[Whether to use full-screen or borderless windowing]
[Whether to use game filter]
[Whether the game window is blocked by external programs]

**Comment by mgsweet** [comment]
Not enough info to regenerate the problem.
