### ISSUE TITLE
GUYS I want to set a hotkey to use that function like caps ,how to make it

### ISSUE THREAD

**Issue by Tomgit1122** [mgsweet/Apex-NoRecoil-2021#220]
GUYS I want to set a hotkey to use that function like caps ,how to make it.Please help lol

**Comment by Milesians** [comment]
I try to make it work , you can  use it from my fork.
I only tested the save action , could you help me test the effect in the game
[my fork](https://github.com/Milesians/Apex-NoRecoil-2021)
It is ONLY check the capslock state for now , if it worked, I will add other keys like scrolllock and numlock.
