### ISSUE TITLE
能否使用离线OCR代替在线的

### ISSUE THREAD

**Issue by martjay** [mgsweet/Apex-NoRecoil-2021#223]
网络原因总是有延迟，有时候识别不出来就没有效果，还得反复切换武器才行

**Comment by fatinghenji** [comment]
OCR?你在用 python 版本的？
ahk 是检测像素点颜色的应该用不上 ocr

**Comment by martjay** [comment]
> 

ahk，因为它总是随机失效，效果时有时无的能不能改善啊

**Comment by fatinghenji** [comment]
> > 
> 
> ahk，因为它总是随机失效，效果时有时无的能不能改善啊

> 纯粹就是识别像素颜色并帮助你移动鼠标。

请仔细阅读项目 readme。ahk 不牵扯 ocr
