### ISSUE TITLE
Cant work with dx12 open

### ISSUE THREAD

**Issue by Milesians** [mgsweet/Apex-NoRecoil-2021#224]
cant work with dx12 open,is the color causing the problem?

**Comment by Eternal-Walnut** [comment]
DX12 is working. close this issue

**Comment by Milesians** [comment]
> DX12 is working. close this issue

I changed weapon but I could not hear the hint (it's not working) with DX12 and debug mode.
I am sure that everything is fine with DX11.
I will try it again tonight.

**Comment by Milesians** [comment]
Confirmed. Not worked with DX12.

**Comment by Milesians** [comment]
I will try to figure it out.

**Comment by Eternal-Walnut** [comment]
Can you record a full-screen video?
And please check your Filter, some filter works normally in DX 11 but cannot work in DX12
Therefore, the color of DX11 and DX12 may not be the same, which may lead to unusable

**Comment by Milesians** [comment]
> Can you record a full-screen video? And please check your Filter, some filter works normally in DX 11 but cannot work in DX12 Therefore, the color of DX11 and DX12 may not be the same, which may lead to unusable
Checked, its caused by color issues,i m too lazy to fix it,so i will use DX11 mode. :D
