### ISSUE TITLE
此软件已被检测

### ISSUE THREAD

**Issue by yuhangwang2** [mgsweet/Apex-NoRecoil-2021#225]
此软件已被检测，一个账号封号，第2个秒封，问了4个人全部封号

**Comment by wurenand** [comment]
真的吗

**Comment by wurenand** [comment]
> 此软件已被检测，一个账号封号，第2个秒封，问了4个人全部封号

真的？

**Comment by yuhangwang2** [comment]
不信可以拿小号测试

**Comment by wurenand** [comment]
> 不信可以拿小号测试

吓人，我昨天还在用。不会被追封吧

**Comment by wurenand** [comment]
> 不信可以拿小号测试

你是用AHK版本被封的？

**Comment by yuhangwang2** [comment]
是

**Comment by yuhangwang2** [comment]
推荐你这2天不要玩游戏之后，不怕封主板或ip,那你继续使用

**Comment by sky5416841** [comment]
![12234](https://user-images.githubusercontent.com/109945433/216776078-1535caad-5925-4715-bd29-c86cce84f591.png)
我打了兩把競技場 靶場也待了10分鐘 也沒見封號

**Comment by 646556341** [comment]
个人试用过，暂时还没有出现封号问题

**Comment by CHN1029** [comment]
我自己修改了部分代码，删除了部分功能以及改了uuid，目前没有事

**Comment by CHN1029** [comment]
我自己修改了部分代码以及uuid，删除了部分功能，现在是2023.2.7，两个账号均没有被封，如果出现异常我回来更新留言

**Comment by Eternal-Walnut** [comment]
對於帳戶封禁，建議使用由自己修改過UUID的版本，而不是Github中的發佈版本
因為Github中的發佈版本可能會有很多人使用，這會導致反作弊記錄其程式特徵

請注意！如果帳戶已被封禁，EAC會記錄你的HWID
這會使你無論是否使用作弊程式帳戶也會被禁止

**Comment by labradorking** [comment]
> 此软件已被检测，一个账号封号，第2个秒封，问了4个人全部封号

請問你有開其他的輔助程式嗎?還是只有開這個

**Comment by CHN1029** [comment]
> > 此软件已被检测，一个账号封号，第2个秒封，问了4个人全部封号
> 
> 請問你有開其他的輔助程式嗎?還是只有開這個

使用的是这个项目，但是我修改删除过很多代码，只保留了最基本的功能。只有pattern和Resolution文件夹，以及一个.ahk运行文件和.ini保存设置的文件。甚至没有hyde.dll，建议修改uuid使用，我目前没有封号。

**Comment by meowmeowheyhey** [comment]
> > > 此软件已被检测，一个账号封号，第2个秒封，问了4个人全部封号
> > 
> > 
> > 請問你有開其他的輔助程式嗎?還是只有開這個
> 
> 使用的是这个项目，但是我修改删除过很多代码，只保留了最基本的功能。只有pattern和Resolution文件夹，以及一个.ahk运行文件和.ini保存设置的文件。甚至没有hyde.dll，建议修改uuid使用，我目前没有封号。
請問如何修改UUID

**Comment by CHN1029** [comment]
> > > > 此软件已被检测，一个账号封号，第2个秒封，问了4个人全部封号
> > > 
> > > 
> > > 請問你有開其他的輔助程式嗎?還是只有開這個
> > 
> > 
> > 使用的是这个项目，但是我修改删除过很多代码，只保留了最基本的功能。只有pattern和Resolution文件夹，以及一个.ahk运行文件和.ini保存设置的文件。甚至没有hyde.dll，建议修改uuid使用，我目前没有封号。
> > 請問如何修改UUID

右键.ahk文件打开方式选择记事本，找到uuid那一行，去网上找一个生成uuid的网站，替换一下就行。

**Comment by meowmeowheyhey** [comment]
> 

請問只用基本的壓槍功能 哪一些檔案是可以刪掉的呢？

**Comment by meowmeowheyhey** [comment]
> > > > > 此软件已被检测，一个账号封号，第2个秒封，问了4个人全部封号
> > > > 
> > > > 
> > > > 請問你有開其他的輔助程式嗎?還是只有開這個
> > > 
> > > 
> > > 使用的是这个项目，但是我修改删除过很多代码，只保留了最基本的功能。只有pattern和Resolution文件夹，以及一个.ahk运行文件和.ini保存设置的文件。甚至没有hyde.dll，建议修改uuid使用，我目前没有封号。
> > > 請問如何修改UUID
> 
> 右键.ahk文件打开方式选择记事本，找到uuid那一行，去网上找一个生成uuid的网站，替换一下就行。

請問只用基本的壓槍功能，哪一些檔案是可以刪掉的呢？

**Comment by mgsweet** [comment]
duplicate to https://github.com/mgsweet/Apex-NoRecoil-2021/issues/72
