### ISSUE TITLE
I have an error running uuid_generator.py with AHK Regarding import uuid, why am I prompted that I did not introduce the class, and how can I resolve the problemWelcome to Apex-NoRecoil-2021 Discussions!

### ISSUE THREAD

**Issue by huazz5** [mgsweet/Apex-NoRecoil-2021#233]

**Comment by huazz5** [comment]
I have an error running uuid_generator.py with AHK
Regarding import uuid, why am I prompted that I did not introduce the class, and how can I resolve the problem

**Comment by ArinLP** [comment]
go wait for update

**Comment by huazz5** [comment]
> go wait for update

ok,thx

**Comment by Milesians** [comment]
if you use the AHK version, u can change uuid variable  in apexmasert.ahk,gui.ahk,green.ahk  youself.

**Comment by mgsweet** [comment]
Run uuid_generator.py with Python3, not AHK lol
