### ISSUE TITLE
Gold Optics help

### ISSUE THREAD

**Issue by 13urning** [mgsweet/Apex-NoRecoil-2021#236]
how does the gold optic feature work? I turned it on and tried it out in the firing range but I dont think it's doing something?

**Comment by DarkShori** [comment]
same with me.. everything works fine ,the autofire, no recoil but this gold optic feature i cant seem to make it work even if i enable it. i tried with wingman and shotgun with gold optics after enable it and i dont notice the difference and its not aim assisting or anything..

**Comment by baoc2** [comment]
It would try to snap to target when mouse1 is pressed.
IMO it's not working really well as it's aim is always a bit off to me.
I feel like it's more like an experimental feature that's nice to have, but no one would actually expect it to be helping much on their gameplay.
