### ISSUE TITLE
压枪无效果

### ISSUE THREAD

**Issue by 1411348064** [mgsweet/Apex-NoRecoil-2021#24]
我运行apexmaster.exe后，1,2切换武器，压枪无效果

**Comment by hitch3ns** [comment]
disable nivida filters if you have it on

**Comment by qiyi71w** [comment]
.

**Comment by 1411348064** [comment]
Is there a solution?

**Comment by Krazyyysa** [comment]
> 有解决办法吗？

你分辨率对不对啊

**Comment by 1411348064** [comment]
1920x1080啊- -无边框

**Comment by Krazyyysa** [comment]
> 1920x1080啊- -无边框

全屏试了？

**Comment by 1411348064** [comment]
试过了，一个样  运行apexmaster.ahk和exe好像都没效果

**Comment by mgsweet** [comment]
> Is there a solution?

The script works just fine to me. Can't help because your question contains not enough context.

**Comment by 1411348064** [comment]
我好像解决了，每把枪都要按shift或者ctrl，是这样么？

**Comment by mgsweet** [comment]
@1411348064 No, please first check the usage [here](https://github.com/mgsweet/Apex-NoRecoil-2021/tree/main/AHK#usage) if you are using the AHK version.
> After running the script, every time you press 1, 2, B, or E, the script will detect your current weapon and provide compensation while you click L Button while holding your R Button.

**Comment by moayadd** [comment]
So everytime I switch to a woapen i click those (L,R) buttons?
