### ISSUE TITLE
update this permission under season 16 please 1280x720

### ISSUE THREAD

**Issue by danza323123123** [mgsweet/Apex-NoRecoil-2021#247]

**Comment by richardzzp** [comment]
#250 更新了新武器的2560x1440和1280x720分辨率

**Comment by danza323123123** [comment]
thank you! but I've already figured out how it works myself

> #250 更新了新武器的2560x1440和1280x720分辨率

**Comment by danza323123123** [comment]
> #250 更新了新武器的2560x1440和1280x720分辨率

I would also like to find out which element of the code is responsible for automatic firing

**Comment by richardzzp** [comment]
你的意思是像p2020和赫姆洛克那种，单点变成连发的吗？
apexmaster.ahk line: 610~613 ; 502~569
