### ISSUE TITLE
AHK version 1.1 important notes

### ISSUE THREAD

**Issue by mgsweet** [mgsweet/Apex-NoRecoil-2021#25]
Hey, guys

I just updated my AHK script which "stole" all the recoil patterns from https://github.com/sayoui001/ApexAHK-Reduce-recoil. (see https://github.com/mgsweet/Apex-NoRecoil-2021/issues/23 for more details about those magic pattern data).

The single-shot-auto-fire feature is a bit aggressive. So if you want to run the script in a safer mode, please make sure you set the `auto_fire` in `setting.ini` to `"off"`. For me, I would go traveling for a few days (national holiday). 

Feel free to report any bugs here. I will check that 5 days later.

Enjoy the new script, cheers!

**Comment by Nymph831** [comment]
Thank you for making it Have a great holiday!

**Comment by Nymph831** [comment]
For wingman, this mode will result in too fast firing.

**Comment by prokiller1199** [comment]
Not sure why, but my game will freeze when i press my left mouse button

**Comment by hitch3ns** [comment]
i have fire mode on off but still auto fire is that problem ?

**Comment by Nymph831** [comment]
> i have fire mode on off but still auto fire is that problem ?

I don't know why, but it's true that he won't close it, but you can delete the single shot line in the code that corresponds to the gun.

**Comment by mgsweet** [comment]
> In the empty hand state and the use of grenades state will have repair I remember the previous version will not

@Nymph831 Set ads_only to `on`. I can't fix that for now. I know that there is a bug that when you press `e` with a grenade in hand, the detection logic would reset the grenade mode to false. I can't detect the whether you are holding the grenade and that is why I can't fix that. Use ads_only can solve this issue, since you don't need to press `R-button` to throw grenade.

**Comment by mgsweet** [comment]
v1.2 is on is way
