### ISSUE TITLE
how to make your own patterns?

### ISSUE THREAD

**Issue by ArinLP** [mgsweet/Apex-NoRecoil-2021#253]
Hello, I would like to ask how to make better patterns, because some weapons are not so perfect and I would like to get them better, is there a video or something like that somewhere ?

**Comment by Asg77596** [comment]
[https://www.unknowncheats.me/forum/apex-legends/467406-method-generating-recoil-patterns-ahk-script-development-testing.html](url)

**Comment by mgsweet** [comment]
See: https://github.com/mgsweet/Apex-NoRecoil-2021/tree/main/AHK/debug/make_recoil
