### ISSUE TITLE
关于金镜功能的问题

### ISSUE THREAD

**Issue by huazz5** [mgsweet/Apex-NoRecoil-2021#256]
1.如何使用金镜功能
2.使用金镜功能时，需不需要更改游戏中的设置
3.如果金镜功能开启成功，效果现象是怎么样的，是跟手柄的辅助瞄准差不多嘛
4.金镜功能，目前支持哪些武器，狙击枪和霰弹枪吗？

谢谢，你们的帮助.

**Comment by Eternal-Walnut** [comment]
1.按下數位0開啟或關閉功能,並且需要按住滑鼠右鍵

2.將遊戲調整為全屏模式

3.功能工作時按下開火瞬間將滑鼠移至荧幕中的紅色

4.所有可以安裝金鏡的武器

並不建議使用此功能，它會瞄準所有紅色，即使不是玩家

**Comment by huazz5** [comment]
> 
谢谢,你的帮忙，我去测试一下
