### ISSUE TITLE
The script may no longer be safe

### ISSUE THREAD

**Issue by TokikiriNanaya** [mgsweet/Apex-NoRecoil-2021#260]
My account is banned. I'm sure I only use this script

**Comment by zhouzikk** [comment]
how long

**Comment by zhouzikk** [comment]
gold_optics && auto_fire?

**Comment by danza323123123** [comment]
I have been using this script since the release, there is no ban in its various versions!!

**Comment by Pachacco99** [comment]
sry，I think it's because you used other software or your machine itself was banned, because EA updated some anti-cheat programs, and I didn't have any problems using it。

**Comment by ueeseer** [comment]
I got banned in two accounts. I wonder that if you directly use the /src/.ahk or you first complied but got banned?

**Comment by TokikiriNanaya** [comment]
> I got banned in two accounts. I wonder that if you directly use the /src/.ahk or you first complied but got banned?

This is not the first time I have been banned. My previous account used this script and also used aimbot. After being banned, I registered a new account and no longer used aimbot, but it was still banned two weeks later

**Comment by natiekafei** [comment]
又没有专业人士，现在是否安全使用

**Comment by ueeseer** [comment]
I believe this script is not safe. I managed to compile and changed the id for my own device. However I still got banned. My suggestion will be that rewrite the code using logitech dll to move the mouse rather using ahk.

**Comment by Pachacco99** [comment]
> 

确保电脑杀毒没有把hyde等用于隐藏的文件被删除或者你也可以使用python版本的，现在的机器码有四个小时的，你可以先注册个小号正常手打四个小时看看。我目前还在一直用，我也没有故意演戏什么的，现在是打到了钻4。如果还是被封那只能说你的电脑可能不适合使用这个软件。

**Comment by mgsweet** [comment]
You can't expect 100% safe when you decide to cheat. For similar topics, pls discuss here: https://github.com/mgsweet/Apex-NoRecoil-2021/discussions/294 .
