### ISSUE TITLE
我也在怀疑，现在是否安全，UUID更换了，新电脑还是封禁

### ISSUE THREAD

**Issue by natiekafei** [mgsweet/Apex-NoRecoil-2021#266]

**Comment by Pachacco99** [comment]
还是那句话。本身机器没有被封禁，也不要与外挂搭配使用还有确保你的软件是从这里下载的且没有被其他人二改的。目前win10 21H2系统没出过毛病，每次他们说拉闸我这里一个号都没有被封过

**Comment by ueeseer** [comment]
> 还是那句话。本身机器没有被封禁，也不要与外挂搭配使用还有确保你的软件是从这里下载的且没有被其他人二改的。目前win10 21H2系统没出过毛病，每次他们说拉闸我这里一个号都没有被封过

我个人有个猜想 是不是你数据不太行 我每次团队死斗杀25个人以上以后就容易被封 不排除是被特定+数据异常两个加在一起导致的拉闸

**Comment by mgsweet** [comment]
See: https://github.com/mgsweet/Apex-NoRecoil-2021/discussions/294
