### ISSUE TITLE
Is anybody been banned for this

### ISSUE THREAD

**Issue by Igors7999** [mgsweet/Apex-NoRecoil-2021#269]
If you were banned, were you able to unban?

**Comment by colinuwu** [comment]
no?

**Comment by zhouzikk** [comment]
my account is baned Q Q

**Comment by zhouzikk** [comment]
AutoHotKey is unsafe

**Comment by Igors7999** [comment]
Have you tried to get unbanned?

**Comment by baoc2** [comment]
make sure both of your hyde files are within the folder when using the ahk edition.
antivirus often delete those files automatically.

**Comment by depirolv** [comment]
Just got banned.

**Comment by wurenand** [comment]
my account is banned about 2 mouths ago

**Comment by mgsweet** [comment]
You can't expect 100% safe when you decide to cheat. For similar topics, pls discuss here: https://github.com/mgsweet/Apex-NoRecoil-2021/discussions/294 .
