### ISSUE TITLE
What's an effective way of finding the correct 3 pixels?

### ISSUE THREAD

**Issue by DNBRMK3** [mgsweet/Apex-NoRecoil-2021#27]
Hi,

Not sure if this is the right place to put this im not a git hub user.

I've been playing around to get 1440p to work with your code... (I'm no developer). All I did was increase the pixel values by 33.333% which works for all the weapons apart from the p2020 or the R99. What's an effective way of finding the correct 3 pixels? 

Happy to share with you the changes if you want to post a working 1440p version.

DNBR

**Comment by VStorm001** [comment]
I tried to get pixels myself, but it didn't seem to work.
Is there a limit on pixel positions?

; heavy weapon
global CAR_PIXELS := [1572, 973, true, 1649, 982, false, 1658, 992, true]

; heavy weapon pattern
global CAR_PATTERN := LoadPattern("CAR.txt")

; then check the weapon type
else if (CheckWeapon (CAR_PIXELS)) {
current_weapon_type := CAR_WEAPON_TYPE
current_pattern := CAR_PATTERN
}

**Comment by mgsweet** [comment]
@VStorm001 Check the diff I made in the commit history. Check those commits for which I add support to new weapons. Or you can just wait till the next update. Feeling tired after going back home during the workday and will update the script this weekend.

**Comment by leafwalktuffy** [comment]
> I tried to get pixels myself, but it didn't seem to work. Is there a limit on pixel positions?
> 
> ; heavy weapon global CAR_PIXELS := [1572, 973, true, 1649, 982, false, 1658, 992, true]
> 
> ; heavy weapon pattern global CAR_PATTERN := LoadPattern("CAR.txt")
> 
> ; then check the weapon type else if (CheckWeapon (CAR_PIXELS)) { current_weapon_type := CAR_WEAPON_TYPE current_pattern := CAR_PATTERN }

CAR_PIXELS := [1605, 970, true, 1586, 973, true, 1605, 971, true]
These three pixels are useful

**Comment by VStorm001** [comment]
> 
> CAR_PIXELS := [1605, 970, true, 1586, 973, true, 1605, 971, true] These three pixels are useful
It still doesn't work.

**Comment by mgsweet** [comment]
@VStorm001 Check the latest commit: https://github.com/mgsweet/Apex-NoRecoil-2021/commit/d66dbd44fe69ee67133fb0e7dc3802b9b5bf5f49

**Comment by VStorm001** [comment]
> @VStorm001 Check the latest commit: [d66dbd4](https://github.com/mgsweet/Apex-NoRecoil-2021/commit/d66dbd44fe69ee67133fb0e7dc3802b9b5bf5f49)

It still doesn't work.

**Comment by mgsweet** [comment]
@VStorm001 Really? Are u using the latest version of the script?

**Comment by mgsweet** [comment]
Here, I would also record the way how to generate `<resolution>.ini` file for the latest version. 

First, use some silly script to map the 1080p pixels to the one you want, for example: from 1080 / 3 * 4 = 1440, so:
``` go
func main() {
	str1 := `havoc_terbocharger = "1621,1006"
devotion_terbocharger = "1650,1007"`
	tmp := strings.Split(str1, "\n")

	fmt.Println(len(tmp))

	for _, v := range tmp {
		t1 := strings.Split(v, " = ")
		res := t1[0] + " = \""
		t2 := strings.Split(t1[1][1: len(t1[1]) - 1], ",")
		for i, v := range t2 {
			t3, _ := strconv.ParseInt(v, 10, 64)
			if t3 > 1 {
				t3 = t3 * 4 / 3
			}
			res += strconv.FormatInt(t3,10)
			if i != len(t2) - 1 {
				res += ","
			}
		}
		res += "\""
		fmt.Println(res)
	}
}
```

Then, run the game and do some checks. For those which cannot work, use the pixel capture approach I mention above to do some more modifications.

**Comment by VStorm001** [comment]
> ```go
> func main() {
> 	str1 := `havoc_terbocharger = "1621,1006"
> devotion_terbocharger = "1650,1007"`
> 	tmp := strings.Split(str1, "\n")
> 
> 	fmt.Println(len(tmp))
> 
> 	for _, v := range tmp {
> 		t1 := strings.Split(v, " = ")
> 		res := t1[0] + " = \""
> 		t2 := strings.Split(t1[1][1: len(t1[1]) - 1], ",")
> 		for i, v := range t2 {
> 			t3, _ := strconv.ParseInt(v, 10, 64)
> 			if t3 > 1 {
> 				t3 = t3 * 4 / 3
> 			}
> 			res += strconv.FormatInt(t3,10)
> 			if i != len(t2) - 1 {
> 				res += ","
> 			}
> 		}
> 		res += "\""
> 		fmt.Println(res)
> 	}
> }
> ```
### how to use this?

**Comment by VStorm001** [comment]
> ```go
> func main() {
> 	str1 := `havoc_terbocharger = "1621,1006"
> devotion_terbocharger = "1650,1007"`
> 	tmp := strings.Split(str1, "\n")
> 
> 	fmt.Println(len(tmp))
> 
> 	for _, v := range tmp {
> 		t1 := strings.Split(v, " = ")
> 		res := t1[0] + " = \""
> 		t2 := strings.Split(t1[1][1: len(t1[1]) - 1], ",")
> 		for i, v := range t2 {
> 			t3, _ := strconv.ParseInt(v, 10, 64)
> 			if t3 > 1 {
> 				t3 = t3 * 4 / 3
> 			}
> 			res += strconv.FormatInt(t3,10)
> 			if i != len(t2) - 1 {
> 				res += ","
> 			}
> 		}
> 		res += "\""
> 		fmt.Println(res)
> 	}
> }
> ```
I tried to output 1280x720, but some weapons didn't work

**Comment by mgsweet** [comment]
> I tried to output 1280x720, but some weapons didn't work
For those not working, you still have to do it manually.
![image](https://user-images.githubusercontent.com/15327389/140675162-e25fcd2d-b020-4c75-af37-454e41c01cc1.png)

**Comment by mgsweet** [comment]
Check this video @VStorm001 @DNBRMK3 : [Apex-NoRecoil-2021 AHK | Customized Resolution](https://www.youtube.com/watch?v=VhpEi4_U3lc)
