### ISSUE TITLE
CAR Pattern

### ISSUE THREAD

**Issue by hitch3ns** [mgsweet/Apex-NoRecoil-2021#28]
will be any update for CAR & new package load ?

**Comment by VStorm001** [comment]
https://github.com/mgsweet/Apex-NoRecoil-2021/issues/6#issuecomment-958636186

**Comment by VStorm001** [comment]
I tried to get pixels myself, but it didn't seem to work.
Is there a limit on pixel positions?

; heavy weapon
global CAR_PIXELS := [1572, 973, true, 1649, 982, false, 1658, 992, true]

; heavy weapon pattern
global CAR_PATTERN := LoadPattern("CAR.txt")

; then check the weapon type
else if (CheckWeapon (CAR_PIXELS)) {
			current_weapon_type := CAR_WEAPON_TYPE
            current_pattern := CAR_PATTERN
		}

**Comment by mgsweet** [comment]
Add TODO to https://github.com/mgsweet/Apex-NoRecoil-2021/issues/6.
