### ISSUE TITLE
这几个选项都是什么功能呢？

### ISSUE THREAD

**Issue by qiutianxianyu** [mgsweet/Apex-NoRecoil-2021#282]

**Comment by qiutianxianyu** [comment]
![c572ec0bdb8bd695dd120a7353aa88d](https://user-images.githubusercontent.com/126447716/233531071-d5a5b916-6128-4ac8-9d48-deda560cdeb3.png)

**Comment by ArinLP** [comment]
auto fire is for automatic clicking of pistols
ads only is that the recoil script is activated only when you aim with the right mouse button 
debug I don't know what it does
trigger only doesn't work for me and I don't use it
gold optic, is less aim assist when you have gold 1x scope on your weapon
and the rest you can see what it does (sens,resolution,colorblind)

**Comment by fengyueZz233** [comment]
哪里可以下载请问.这里只有源码

**Comment by Eternal-Walnut** [comment]
Trigger only means that recoil control will be performed only when the selected item box's key is activated

Debug is only for debugging purposes and does not need to be enabled
