### ISSUE TITLE
昨天开始宏大封，有被封的吗

### ISSUE THREAD

**Issue by hikariaoe** [mgsweet/Apex-NoRecoil-2021#285]
昨天开始宏大封，有被封的吗

**Comment by fatinghenji** [comment]
那里消息？来源可靠度有多少？用这个以来听说很多次封宏了，但是一次没挨过

**Comment by hikariaoe** [comment]
你在B站上搜宏看最新的视频，昨天封了3W多个，TB店家都跑了

**Comment by LR-KING** [comment]
> 那里消息？来源可靠度有多少？用这个以来听说很多次封宏了，但是一次没挨过

封的基本上都是没做隐藏还有读写游戏内存的宏

**Comment by DAI-HY** [comment]
小号无了

**Comment by zzxqy** [comment]
封了

**Comment by mgsweet** [comment]
See: https://github.com/mgsweet/Apex-NoRecoil-2021/discussions/294
