### ISSUE TITLE
ADS 模式压枪问题

### ISSUE THREAD

**Issue by fengyueZz233** [mgsweet/Apex-NoRecoil-2021#286]
ADS 模式下为长按`鼠标右键`触发压枪
那请问可以改成`鼠标侧键`嘛?
可以的话该如何设置呢
非常感谢!

**Comment by Eternal-Walnut** [comment]
replace [RButton](https://github.com/mgsweet/Apex-NoRecoil-2021/blob/main/AHK/src/apexmaster.ahk#L517) to "XButton1" or "XButton2"

**Comment by fengyueZz233** [comment]
好了,感谢
