### ISSUE TITLE
This will help you develop over the script in the future.

### ISSUE THREAD

**Issue by Igors7999** [mgsweet/Apex-NoRecoil-2021#29]
You can do pixel recognition in the new version of the script for the regular version of the weapon from.Care Package. For example, Spitfire or Alternator or G7 will return to earth sometime in the future and their color will change from red. This will help you develop over the script in the future.

**Comment by mgsweet** [comment]
Do you mean doing pixel recognition without detecting what kind of weapon it is (e.g. light weapon)?

**Comment by Igors7999** [comment]
yes. 
For example, in the following seasons, the spitfire will be removed from the Care Package and it will stand on heavy ammunition and its texture will change from red to blue.

**Comment by mgsweet** [comment]
only using three pixels may cause conflict, have no plan on this issue, close~
