### ISSUE TITLE
Sella?

### ISSUE THREAD

**Issue by RaphielHS** [mgsweet/Apex-NoRecoil-2021#308]
Anyone knows what is "Sella"? is it the Mobile Minigun "Sheila" from Rampart or what

**Comment by RaphielHS** [comment]
It's featured 15 times in the code

**Comment by reibc** [comment]
> Anyone knows what is "Sella"? is it the Mobile Minigun "Sheila" from Rampart or what

it's rampart's ultimate ability

**Comment by RaphielHS** [comment]
> > Anyone knows what is "Sella"? is it the Mobile Minigun "Sheila" from Rampart or what
> 
> it's rampart's ultimate ability

OOH, thanks for the information
