### ISSUE TITLE
AHK v1.2.2 is released! Now the script supports both 2k and 4k!

### ISSUE THREAD

**Issue by mgsweet** [mgsweet/Apex-NoRecoil-2021#33]
Hey guys!

I know people keep asking me to support multiple resolutions. Now, it comes! Moreover, I build a GUI to help u guys do the configuration thing. 

For v1.2.2, the script only support 1080x1920, 2560x1440 and 3840x2160. Sorry, these days I don't have much time to play the game myself. I hope u guys can download the latest version and do some more real game testing. Please report any bugs here. Thanks!

Cheers!
mgsweet

**Comment by mgsweet** [comment]
@krampus-nuggets @filen1 @VStorm001 @Nymph831 @hitch3ns manually info these guys to ask for opinions.

**Comment by hitch3ns** [comment]
i have family situation going on i will test the new script later on ... big thanks for your support and efforts

**Comment by VStorm001** [comment]
it great!
I'm trying to make a version of another resolution.

**Comment by Nymph831** [comment]
It's great. The game will be fun after this not-so-fun new map passes.

**Comment by Nymph831** [comment]
If I want to support weapons in blue-blind mode, how do I change the color?

**Comment by mgsweet** [comment]
> If I want to support supply drop weapon weapons in blue-blind mode, how do I change the color?

Change those colors to yours. Start from here.
https://github.com/mgsweet/Apex-NoRecoil-2021/blob/b47eff154f9287dd8dde6fa2c83ddc101c07cca7/AHK/src/apexmaster.ahk#L52

**Comment by Monswon** [comment]
Hi need help for stretch resolution 1728x1080 generated this pixels using the rough generator however it isn't detecting the weapon it is saying default for all weapon

[pixels]
weapon1 = "1369,1040"
weapon2 = "1640,1039"
r99 = "1425,977,1,1484,980,0,1525,982,1"       
r301 = "1419,970,1,1491,977,0,1523,978,1"      
re45 = "1445,975,1,1476,981,0,1495,1004,1"     
p2020 = "1444,969,1,1468,982,0,1486,1005,1"    
g7 = "1415,975,1,1493,981,0,1532,990,1"        
flatline = "1413,975,1,1471,980,0,1498,993,1"  
prowler = "1448,990,1,1471,984,0,1505,976,1"   
hemlok = "1445,983,1,1483,985,0,1519,986,1"    
rampage = "1403,976,1,1481,984,0,1531,983,1"   
wingman = "1442,984,1,1480,985,0,1492,1001,1"  
lstar = "1421,994,1,1476,990,0,1500,969,1"     
devotion = "1530,971,1,1495,980,0,1404,972,1"  
volt = "1479,981,0,1426,976,1,1512,971,1"      
havoc = "1490,996,1,1492,985,0,1473,962,1"     
spitfire = "1523,972,1,1486,989,1,1480,962,1"  
alternator = "1453,979,1,1477,980,1,1481,978,0"
car = "1444,970,1,1427,973,1,1444,971,1"       
havoc_turbocharger = "1460,1014"
devotion_turbocharger = "1485,1014"

**Comment by Nymph831** [comment]
> > If I want to support supply drop weapon weapons in blue-blind mode, how do I change the color?
> 
> @Nymph831 Change those colors to yours. Start from here.
> 
> https://github.com/mgsweet/Apex-NoRecoil-2021/blob/b47eff154f9287dd8dde6fa2c83ddc101c07cca7/AHK/src/apexmaster.ahk#L52


Yes, I tried to extract the colour from the weapon bar, but that was wrong.

**Comment by alloidiota** [comment]
1680x1050 support please!

**Comment by mgsweet** [comment]
> > > If I want to support supply drop weapon weapons in blue-blind mode, how do I change the color?
> > 
> > 
> > @Nymph831 Change those colors to yours. Start from here.
> > https://github.com/mgsweet/Apex-NoRecoil-2021/blob/b47eff154f9287dd8dde6fa2c83ddc101c07cca7/AHK/src/apexmaster.ahk#L52
> 
> Yes, I tried to extract the colour from the weapon bar, but that was wrong.

@Nymph831 By default, AHK uses BGR format instead of RGB, you can use the `get_color.ahk` lying in debug folder to get color. Press `T` when you want to know the info of your cursor.

**Comment by mgsweet** [comment]
@alloidiota saying default means that the detection logic is working. Maybe you can try the gen.py one more time. I have updated its logic to let it generate pixels based on 1080p's data (before is based on 4k).

**Comment by mgsweet** [comment]
v1.2.4 is now released.
