### ISSUE TITLE
New SCRIPT FUNCTIONS.

### ISSUE THREAD

**Issue by Igors7999** [mgsweet/Apex-NoRecoil-2021#34]
What do you think about adding an aim asist for gold optics for submachine guns? This function can be done in the likeness of the red pixel aimbot script. It works like pixel hunting because golden optics changes the color of enemies completely to red. It is full legit and safe. It doesn't work as an aim bot. It just slowly brings up the red pixels. This script needs more color codes as it won't work because these color codes are wrong. This is just an example of how you can create such a script.

init:
#NoEnv
#SingleInstance, Force
#Persistent
#InstallKeybdHook
#UseHook
#KeyHistory, 0
#HotKeyInterval 1
#MaxHotkeysPerInterval 127
version = 1.0
traytip, GamerGuyAHK %version%, Running in background!, 5, 1
Menu, tray, NoStandard
Menu, tray, Tip, Sharpshooter %version%
Menu, tray, Add, Sharpshooter %version%, return
Menu, tray, Add
Menu, tray, Add, Help, info
Menu, tray, Add, Exit, exit
SetKeyDelay,-1, 1
SetControlDelay, -1
SetMouseDelay, -1
SetWinDelay,-1
SendMode, InputThenPlay
SetBatchLines,-1
ListLines, Off
CoordMode, Pixel, Screen, RGB
CoordMode, Mouse, Screen
PID := DllCall("GetCurrentProcessId")
Process, Priority, %PID%, High
 
EMCol := 0xc33b36,0xc93932
ColVn := 2
AntiShakeX := (A_ScreenHeight // 160)
AntiShakeY := (A_ScreenHeight // 128)
ZeroX := (A_ScreenWidth // 2)
ZeroY := (A_ScreenHeight // 2)
CFovX := (A_ScreenWidth // 8)
CFovY := (A_ScreenHeight // 64)
ScanL := ZeroX - CFovX
ScanT := ZeroY
ScanR := ZeroX + CFovX
ScanB := ZeroY + CFovY
NearAimScanL := ZeroX - AntiShakeX
NearAimScanT := ZeroY - AntiShakeY
NearAimScanR := ZeroX + AntiShakeX
NearAimScanB := ZeroY + AntiShakeY
 
Loop, {
    KeyWait, RButton, D
    PixelSearch, AimPixelX, AimPixelY, NearAimScanL, NearAimScanT, NearAimScanR, NearAimScanB, EMCol, ColVn, Fast RGB
    if (!ErrorLevel=0) {
        loop, 10 {
            PixelSearch, AimPixelX, AimPixelY, ScanL, ScanT, ScanR, ScanB, EMCol, ColVn, Fast RGB
            AimX := AimPixelX - ZeroX
            AimY := AimPixelY - ZeroY
            DirX := -1
            DirY := -1
            If ( AimX > 0 ) {
                DirX := 1
            }
            If ( AimY > 0 ) {
                DirY := 1
            }
            AimOffsetX := AimX * DirX
            AimOffsetY := AimY * DirY
            MoveX := Floor(( AimOffsetX ** ( 1 / 2 ))) * DirX
            MoveY := Floor(( AimOffsetY ** ( 1 / 2 ))) * DirY
            DllCall("mouse_event", uint, 1, int, MoveX * 1.5, int, MoveY, uint, 0, int, 0)
        }
    }
}
 
Pause:: pause
return:
goto, init
 
info:
msgbox, 0, Sharpsooter %version%, Made by ANUS RAMMER`nOverwatch must be running in borderless windowed mode.`nPress pause key to pause this program.`nLeft click automatically aims down target near the center of the screen.`nRecommended for near distance(~15m) and full-auto weapons.
return
 
exit:
exitapp

**Comment by mgsweet** [comment]
Already support in v1.2.4. Only support shotgun for now. For all weapon, see: [Apex-NoRecoil-2021/AHK/debug/gold_optics_assist.ahk](https://github.com/mgsweet/Apex-NoRecoil-2021/blob/main/AHK/debug/gold_optics_assist.ahk)
