### ISSUE TITLE
New SCRIPT FUNCTIONS.

### ISSUE THREAD

**Issue by Igors7999** [mgsweet/Apex-NoRecoil-2021#41]
What do you think about adding a zoom feature to the script? This feature can be very useful for long-range shooting. I will write an example of how this can be done. In order for the recoil scripts to work while shooting through the zoom, it is necessary to make sure that during the zoom the script remembers the last selected weapons. Unlike the example I found for cs:go, for apex, the hotkeys num+ and num - to zoom in and out of the optics would be better suited. It is also possible to make the sensitivity of the mouse during zoom less (if it is possible to do so)
![1234](https://user-images.githubusercontent.com/92954552/141849641-58bcd31f-9828-4e14-b2e0-95faabf9e23a.jpg)
![123](https://user-images.githubusercontent.com/92954552/141849670-9a643e26-5bae-4a40-afa5-5693d0062a99.png)

;Autohotkey key legend
;  # Windows Key
;  ^ Control
;  ! Alt
;  + Shift

#NoEnv 
magmin=0
SendMode Event
SetWorkingDir %A_ScriptDir%

;-- Magnifier
!Alt:: sendinput #{NumpadAdd} ;zoom in
+WheelDown:: sendinput #{NumpadSub} ;zoom out
F7:: ;toggle Magnifier visibility
 if magmin=0
  {
  WinMinimize, ahk_class MagUIClass
  WinHide, ahk_class MagUIClass
  magmin=1
  }
 else
  {
  WinShow, ahk_class MagUIClass
  magmin=0
  }
return

**Comment by VStorm001** [comment]
>What do you think about adding a zoom feature to the script? ~

Need to change the result of the pattern.

**Comment by mgsweet** [comment]
Not sure if I would add this in the future. I will take a trial if I have time.
