### ISSUE TITLE
AHK v1.2.4 is released! Comes with a powerful feature.

### ISSUE THREAD

**Issue by mgsweet** [mgsweet/Apex-NoRecoil-2021#43]
# Release notes
- support 3030
- update patterns
- new feature: gold optics shotgun aimbot

# How to use the new feature:
- Tick the op_gold_optics (Aim asist for gold optics for shotgun.) 
- Go to fire range, pick a shotgun and gold optics.
- You will find that Mozambique is very OP with this feature.

For Those who tick the op_gold_optics option, I suggest the following setting:
![image](https://user-images.githubusercontent.com/15327389/142762792-afdd8861-1ad7-45a0-bc22-7b4994b3aa97.png)
The reason is to avoid confusing the pixel search process.

# Credit
The idea is from @Igors7999 . Check: https://github.com/mgsweet/Apex-NoRecoil-2021/issues/34

**Comment by hitch3ns** [comment]
will it work with bloodhound ult ?

**Comment by filen1** [comment]
I suggest using hotkey that pauses script function for the aim assist. It attracts to mundane things like the tree in the "The Tree" POI, red loot capsules, and I suspect even the full inventory popup and no ammo pop up.

@hitch3ns yes I believe it does, and maybe even with his scan

**Comment by mgsweet** [comment]
> will it work with bloodhound ult ?

That feature is kind of pre-release. I know it has many issues. Will need some more iteration to get it to function well. Currently, I don't have much idea to make it better.

**Comment by prokiller1199** [comment]
u mean v1.2.4 in the title right.

**Comment by VStorm001** [comment]
>new feature: gold optics shotgun aimbot

Can add this new feature to support all gun that can use 1x digital threat.

**Comment by mgsweet** [comment]
@VStorm001 Actually limiting this feature to only support shotgun need extra work. The experience of this feature on other kinds of weapons is quite bad...

**Comment by VStorm001** [comment]
>The experience of this feature on other kinds of weapons is quite bad...

I think the wingman is a good fit.

**Comment by mgsweet** [comment]
> I think the wingman is a good fit.

@VStorm001 I did expect it to be good. But practice tells me it's not. Comment out the following line. 

https://github.com/mgsweet/Apex-NoRecoil-2021/blob/21a4cc95d194c02b4c15d7ed30a465c83fec92c3/AHK/src/apexmaster.ahk#L264

**Comment by Ramzes2488** [comment]
Hello, I have a problem with the cheat. In this cheat, there is no recoil on such weapons as: changer and speedfire. Thanks in advance for answering my question)

**Comment by SiLeNT-Sooul** [comment]
How do you think about add auto detect like 5hz.
It didn't detect my gun when i use superglide or other movements.

**Comment by VStorm001** [comment]
> How do you think about add auto detect rate 5hz.

I think this will cause the game to lag. 
> It didn't detect my gun when i use superglide or other movements.

u can tap 1,2,E,R or (any key u want to add) before fire.

**Comment by mgsweet** [comment]
> How do you think about add auto detect rate 5hz.

The cost of detection actually is quite low. You can even let it detect your weapon when you try to shoot (bind LMB). But in this way, it can't tell whether you are holding a grenade or shooting.

**Comment by Ramzes2488** [comment]
and can I ask you about one more function?  you can add anti-recoil to a specific button so that you can customize it for yourself.  Thank you in advance)

**Comment by VStorm001** [comment]
>  specific button

p::Pause🤔

**Comment by Ramzes2488** [comment]
> >  specific button
> 
> ```
> p::Pause
> ```
> 🤔
> 
> >Q1 ~
> >Q2 ~
> 
> @Ramzes2488 Do u have a core of your questions?

there is no anti-recoil on the flatline (I confused the speedfire and the flatline😕) and on the changer.  You cannot put your button for anti-recoil

**Comment by VStorm001** [comment]
> there is no anti-recoil on the flatline ～

Does the resolution of screen match the script?
>You cannot put your button for anti-recoil

u can found it on [UC](https://www.unknowncheats.me/forum/apex-legends/)

**Comment by filen1** [comment]
How likely is it to be banned for 'aim botting' with this... I tweaked the ahk settings a bit and it now headshots about 25% of the time. A lot of the time I get double wingman headshots on someone, or a ton of mozambique headshots. It worries me a bit :|

**Comment by VStorm001** [comment]
>the new weapon is not recognized.

u can comment out this line to check the current weapon. 
https://github.com/mgsweet/Apex-NoRecoil-2021/blob/main/AHK/src/apexmaster.ahk#L311-L311

**Comment by filen1** [comment]
> How likely is it to be banned for 'aim botting' with this... I tweaked the ahk settings a bit and it now headshots about 25% of the time. A lot of the time I get double wingman headshots on someone, or a ton of mozambique headshots. It worries me a bit :|

Do not use the gold optics feature. Just got banned after 22~ arena games, not reported by my own teammates, just high headshot % or the mouse movements I suppose. Used p2020, mozam, volt, prowler, r99, mastiff, wingman

**Comment by mgsweet** [comment]
@filen1 can you share your settings to let me do some check. If my test account also got banned, I would remove it in 1.2.5. Thanks.

**Comment by filen1** [comment]
@mgsweet sent you the specifics on UC in a private message

**Comment by filen1** [comment]
> > How likely is it to be banned for 'aim botting' with this... I tweaked the ahk settings a bit and it now headshots about 25% of the time. A lot of the time I get double wingman headshots on someone, or a ton of mozambique headshots. It worries me a bit :|
> 
> Do not use the gold optics feature. Just got banned after 22~ arena games, not reported by my own teammates, just high headshot % or the mouse movements I suppose. Used p2020, mozam, volt, prowler, r99, mastiff, wingman

Banned on alt account in less games, only burst firing r99(no more than 100dmg a time). Could be because trace files/same IP etc. First acc banned at plat 4 this one banned at gold 1. 3rd acc not banned, only norecoil. I think its the accuracy, its unrealistic, that plus the headshot %, otherwise its just the weird mouse movements over anything red lol

**Comment by mgsweet** [comment]
> Banned on alt account in less games, only burst firing r99(no more than 100dmg a time). Could be because trace files/same IP etc. First acc banned at plat 4 this one banned at gold 1. 3rd acc not banned, only norecoil. I think its the accuracy, its unrealistic, that plus the headshot %, otherwise its just the weird mouse movements over anything red lol

Thanks, will remove it this weekend.

**Comment by mgsweet** [comment]
@filen1 I play a ton of arena games with the gold optics feature (only shotgun) and haven't got banned yet. I use a switch button to control the feature in my personal script. I think the way you use it may be too aggressive.

**Comment by filen1** [comment]
You're right, I've been using it on 3rd account with settings that are much more loose aim assist that doesn't lock onto heads.  Using SMG and Snipers and not banned so far. I'll edit once (if) I make it to platinum so we know if its safer or not

**Comment by CplusBest** [comment]
Unfortunately, I am banned after 2 games. I think the main reason is that I used the function of "gold optics feature".  Actually I found someone use the same software. Some merchants copy your work and add login program to sell it and they even donot remove the link at the bottom of the exe file. The only difference is that their version lacks of "gold optics feature", so I guess this is the main reason.

**Comment by mgsweet** [comment]
v1.2.5 released.

**Comment by mgsweet** [comment]
@filen1 

Actually, I am not so sure what is going on now. I created a new test account and tested with that feature and it was banned in level 11. I did pick shotgun with golden optics but didn't kill any people with it. Maybe they can detect whether other processes are searching colours?

Maybe the whole script is on their black list? Need more game tests on v1.2.5 to see what is going on:(

**Comment by hitch3ns** [comment]
@mgsweet maybe get back to old img detection instead of colors ?

**Comment by filen1** [comment]
> @filen1
> 
> Actually, I am not so sure what is going on now. I created a new test account and tested with that feature and it was banned in level 11. I did pick shotgun with golden optics but didn't kill any people with it. Maybe they can detect whether other processes are searching colours?
> 
> Maybe the whole script is on their black list? Need more game tests on v1.2.5 to see whether no-recoil-only has problem

I use the raw ahk files since its safer. I think the exe has a signature(?) or something they can detect that makes it extremely obvious once they know about it. If you want I can give you the gold optics settings I use now.

**Comment by hitch3ns** [comment]
@filen1 may you share it please ? my discord is HiTcH-1#6265
