### ISSUE TITLE
Color aimbot glitch

### ISSUE THREAD

**Issue by Igors7999** [mgsweet/Apex-NoRecoil-2021#44]
When you hit the target, the damage done is shown. The sight is magnified by these numbers. Because of this, the sight goes up. To fix this, you can change just change the color filter in the game settings. (the tritanopia filter is the best of all and many players play with it) But after changing the filter, the script stops recognizing spitfire, ALTERNATOR and G7. Therefore, for these weapons, the patterns without recoil do not work. To fix this, you need to add other pixels for recognition. 

![2](https://user-images.githubusercontent.com/92954552/142775083-2bbf8463-630b-458d-8bc6-bbab88cfb93d.jpg)
![3](https://user-images.githubusercontent.com/92954552/142775089-49e33646-5f26-46d3-b4c3-253ec048041a.jpg)

**Comment by mgsweet** [comment]
That is why I suggest:
![image](https://user-images.githubusercontent.com/15327389/142831639-88b931f0-7d8e-41f2-a1dd-13e4b80da0dc.png)

**Comment by mgsweet** [comment]
Changing the default detect color may affect too many users. I may add color blind mode config in the future version.

**Comment by Igors7999** [comment]
> Changing the default detect color may affect too many users. I may add color blind mode config in the future version.


Yes, that's a great idea! Thank you for your diligence and development of the script. It's really not an easy job. Good luck to you in the future.
