### ISSUE TITLE
op_gold_optics这个功能是什么效果？

### ISSUE THREAD

**Issue by ricerin** [mgsweet/Apex-NoRecoil-2021#45]
在训练场里尝试了半天都没发现有啥区别，还是说我改过画质文件导致功能无法正常运行？

**Comment by VStorm001** [comment]
> 在训练场里尝试了半天都没发现有啥区别，还是说我改过画质文件导致功能无法正常运行？

数位威胁的辅助自瞄(目前只有霰弹)

**Comment by ricerin** [comment]
> > 在训练场里尝试了半天都没发现有啥区别，还是说我改过画质文件导致功能无法正常运行？
> 
> 金色倍镜的辅助自瞄(目前只有霰弹)

和我理解的是一样的，但我在训练场尝试下所有的霰弹带金镜都无法触发

**Comment by prokiller1199** [comment]
> > > 在训练场里尝试了半天都没发现有啥区别，还是说我改过画质文件导致功能无法正常运行？
> > 
> > 
> > 金色倍镜的辅助自瞄(目前只有霰弹)
> 
> 和我理解的是一样的，但我在训练场尝试下所有的霰弹带金镜都无法触发

配置文件开了吗？gui也可以

**Comment by ricerin** [comment]
> > > > 在训练场里尝试了半天都没发现有啥区别，还是说我改过画质文件导致功能无法正常运行？
> > > 
> > > 
> > > 金色倍镜的辅助自瞄(目前只有霰弹)
> > 
> > 
> > 和我理解的是一样的，但我在训练场尝试下所有的霰弹带金镜都无法触发
> 
> 配置文件开了吗？gui也可以

bin里的exe，src里的ahk，还有文件夹外面那个单独的exe都试过了，都是开的，setting里也改成1了，没反应

**Comment by prokiller1199** [comment]
> > > > > 在训练场里尝试了半天都没发现有啥区别，还是说我改过画质文件导致功能无法正常运行？
> > > > 
> > > > 
> > > > 金色倍镜的辅助自瞄(目前只有霰弹)
> > > 
> > > 
> > > 和我理解的是一样的，但我在训练场尝试下所有的霰弹带金镜都无法触发
> > 
> > 
> > 配置文件开了吗？gui也可以
> 
> bin里的exe，src里的ahk，还有文件夹外面那个单独的exe都试过了，都是开的，setting里也改成1了，没反应

有用其他颜色吗？色盲模式？

**Comment by ricerin** [comment]
> 

没开色盲试过，开了色盲也试过，伤害数字也关了

**Comment by prokiller1199** [comment]
> > 
> 
> 没开色盲试过，开了色盲也试过，伤害数字也关了

那我不知道了 我试过是可以用的

**Comment by VStorm001** [comment]
> 还是说我改过画质文件导致功能无法正常运行？
你改了啥？

**Comment by ricerin** [comment]
> > 还是说我改过画质文件导致功能无法正常运行？
> 
> 你改了啥？

可以用了，谢谢大佬，问题好像是出在那个改不了设置文件的主程序，重启了一下电脑就能用了

**Comment by liubei97** [comment]
可以加入其他武器吗

**Comment by mgsweet** [comment]
Problem solved. For the last question, check https://github.com/mgsweet/Apex-NoRecoil-2021/issues/43
