### ISSUE TITLE
请求增加一个自定义检测键位的功能

### ISSUE THREAD

**Issue by 2910894473** [mgsweet/Apex-NoRecoil-2021#46]
在训练场测试了下1.24和1.23版本，发现脚本只有在按下1，2和e键的时候会检测目前的武器。希望可以增加一个自定义检测键位的功能。

**Comment by VStorm001** [comment]
> 在训练场测试了下1.24和1.23版本，发现脚本只有在按下1，2和e键的时候会检测目前的武器。希望可以增加一个自定义检测键位的功能。

自己加就行了,不难

**Comment by 2910894473** [comment]
> > 在训练场测试了下1.24和1.23版本，发现脚本只有在按下1，2和e键的时候会检测目前的武器。希望可以增加一个自定义检测键位的功能。
> 
> 自己加就行了,不难 https://github.com/mgsweet/Apex-NoRecoil-2021/blob/main/AHK/src/apexmaster.ahk#L323-L323

明白了，谢谢
