### ISSUE TITLE
Automatic Identification 

### ISSUE THREAD

**Issue by Aumopko** [mgsweet/Apex-NoRecoil-2021#48]
You can upload a version with automatic recognition and one without automatic recognition
Did not automatically recognize that switch with hotkey

**Comment by CplusBest** [comment]
I think mgsweet detect the type of a weapon by recognizing the pixel area of  the  weapon's location. But the grammar of AHK is strange. I even do not know where is the funtion: "LoadPixel" from. I have read another ahk file using hotkey. It use such line to associate weapon with hotkey.
Hotkey, ~$*%bind_re%, re45

**Comment by mgsweet** [comment]
@CplusBest I did implement `LoadPixel` in my script. Using some plugins in vscode can help you navigate to the function definition.

**Comment by mgsweet** [comment]
@Aumopko For script without automatic recognition, the logic will be quite different. I personally would not provide. But you can find some idea on how to make a hotkey-only script from: https://github.com/thyaguster/NoRecoilApex
