### ISSUE TITLE
关于后座力参数的格式

### ISSUE THREAD

**Issue by VStorm001** [mgsweet/Apex-NoRecoil-2021#5]
或许你可以将格式改成这样，这样可以编辑每发子弹的延迟

[0,0,60]
x := strsplit(active_pattern[a_index],",")[1]
y := strsplit(active_pattern[a_index],",")[2]
t := strsplit(active_pattern[a_index],",")[3]

dllcall("mouse_event","UInt",0x01,"UInt",x*modifier,"UInt",y*modifier)
sleep t

**Comment by VStorm001** [comment]
我认为你可以将搜索区域定在同一个范围，只擷取特定範圍的圖像
https://github.com/CharlesDankoff/ultra_secret_scripts/tree/master/weapon_data

**Comment by mgsweet** [comment]
> 我认为你可以将搜索区域定在同一个范围，只擷取特定範圍的圖像
> https://github.com/CharlesDankoff/ultra_secret_scripts/tree/master/weapon_data

可以的，确实人工取色是比较麻烦

**Comment by mgsweet** [comment]
> 我认为你可以将搜索区域定在同一个范围，只擷取特定範圍的圖像
> https://github.com/CharlesDankoff/ultra_secret_scripts/tree/master/weapon_data

可以的，确实人工取色是比较麻烦

**Comment by mgsweet** [comment]
> 或许你可以将格式改成这样，这样可以编辑每发子弹的延迟
> 
> [0,0,60]
> x := strsplit(active_pattern[a_index],",")[1]
> y := strsplit(active_pattern[a_index],",")[2]
> t := strsplit(active_pattern[a_index],",")[3]
> 
> dllcall("mouse_event","UInt",0x01,"UInt",x_modifier,"UInt",y_modifier)
> sleep t

resolved

**Comment by mgsweet** [comment]
取色优化暂时不会做了，一个原因是图片太多压缩包下载太大，第二个原因是每次读图片开销大，第三个原因是目前整体效果还不错没有改的动力（懒）
