### ISSUE TITLE
AHK v1.2.5: gold-optics aim bot is now removed.

### ISSUE THREAD

**Issue by mgsweet** [mgsweet/Apex-NoRecoil-2021#52]

**Comment by CplusBest** [comment]
Are there some differences between ver 1.2.5 and ver 1.2.3,? I mean you have removed the new features.

**Comment by mgsweet** [comment]
@CplusBest compared to v1.2.3, v1.2.5 has 
- better patterns
- support p3030
- support a new resolution setting

See: https://github.com/mgsweet/Apex-NoRecoil-2021/tree/main/AHK#update

**Comment by prokiller1199** [comment]
[https://github.com/mgsweet/Apex-NoRecoil-2021/blob/main/AHK/bin/settings.ini](url) resolution should be 1920x1080

**Comment by Ramzes2488** [comment]
the recoil of the speedfire and the flatline are identical, what is the problem to copy the recoil code from the speedfire and put it on a flatline that does not have anti-recoil

**Comment by mgsweet** [comment]
v1.2.6 released. Check: https://github.com/mgsweet/Apex-NoRecoil-2021/issues/69
