### ISSUE TITLE
How to expand more resolution support

### ISSUE THREAD

**Issue by chenzijian0** [mgsweet/Apex-NoRecoil-2021#54]
我一般使用 1920 X  1440 分辨率进行游戏 但是现在并没有该分辨率的支持
是否能简单解释一下 如何进行不同分辨率下的像素标记

I generally use 1920 X 1440 resolution to play games, but there is no support for this resolution now.
Can you explain how to mark pixels at different resolutions

**Comment by mgsweet** [comment]
https://github.com/mgsweet/Apex-NoRecoil-2021/tree/main/AHK#how-to-modify-the-code
