### ISSUE TITLE
About golden optics feature.

### ISSUE THREAD

**Issue by Igors7999** [mgsweet/Apex-NoRecoil-2021#55]
You can try to do this function again. You made it as an aimbot. And that's why people could get banned. You can make this function as an aimasist. This means it will be aimed at the target slightly and without sudden movements (like aimasist for ps5 and xbox) This can be done by changing the parameter ColVn := 2 I have been playing with this ahk aimasist since season 2. And my account has never been banned. You can also make this function turn on only after the golden optics on your weapon are detected. This can be done in the same way as weapon recognition via pixelhunt. Only in this case, the script will recognize the yellow pixel on the weapon icon. To be honest, my friends and I didn't get banned for your more powerful script.

init:
#NoEnv
#SingleInstance, Force
#Persistent
#InstallKeybdHook
#UseHook
#KeyHistory, 0
#HotKeyInterval 1
#MaxHotkeysPerInterval 127
version = 1.0
traytip, GamerGuyAHK %version%, Running in background!, 5, 1
Menu, tray, NoStandard
Menu, tray, Tip, Sharpshooter %version%
Menu, tray, Add, Sharpshooter %version%, return
Menu, tray, Add
Menu, tray, Add, Help, info
Menu, tray, Add, Exit, exit
SetKeyDelay,-1, 1
SetControlDelay, -1
SetMouseDelay, -1
SetWinDelay,-1
SendMode, InputThenPlay
SetBatchLines,-1
ListLines, Off
CoordMode, Pixel, Screen, RGB
CoordMode, Mouse, Screen
PID := DllCall("GetCurrentProcessId")
Process, Priority, %PID%, High

EMCol := 0xc33b36,0xc93932
ColVn := 2
AntiShakeX := (A_ScreenHeight // 160)
AntiShakeY := (A_ScreenHeight // 128)
ZeroX := (A_ScreenWidth // 2)
ZeroY := (A_ScreenHeight // 2)
CFovX := (A_ScreenWidth // 8)
CFovY := (A_ScreenHeight // 64)
ScanL := ZeroX - CFovX
ScanT := ZeroY
ScanR := ZeroX + CFovX
ScanB := ZeroY + CFovY
NearAimScanL := ZeroX - AntiShakeX
NearAimScanT := ZeroY - AntiShakeY
NearAimScanR := ZeroX + AntiShakeX
NearAimScanB := ZeroY + AntiShakeY

Loop, {
KeyWait, RButton, D
PixelSearch, AimPixelX, AimPixelY, NearAimScanL, NearAimScanT, NearAimScanR, NearAimScanB, EMCol, ColVn, Fast RGB
if (!ErrorLevel=0) {
loop, 10 {
PixelSearch, AimPixelX, AimPixelY, ScanL, ScanT, ScanR, ScanB, EMCol, ColVn, Fast RGB
AimX := AimPixelX - ZeroX
AimY := AimPixelY - ZeroY
DirX := -1
DirY := -1
If ( AimX > 0 ) {
DirX := 1
}
If ( AimY > 0 ) {
DirY := 1
}
AimOffsetX := AimX * DirX
AimOffsetY := AimY * DirY
MoveX := Floor(( AimOffsetX ** ( 1 / 2 ))) * DirX
MoveY := Floor(( AimOffsetY ** ( 1 / 2 ))) * DirY
DllCall("mouse_event", uint, 1, int, MoveX * 1.5, int, MoveY, uint, 0, int, 0)
}
}
}

Pause:: pause
return:
goto, init

info:
msgbox, 0, Sharpsooter %version%, Made by ANUS RAMMERnOverwatch must be running in borderless windowed mode.nPress pause key to pause this program.nLeft click automatically aims down target near the center of the screen.nRecommended for near distance(~15m) and full-auto weapons.
return

exit:
exitapp

**Comment by mgsweet** [comment]
I may make a script only for this feature. For those who decide to take the risk, they can run both scripts.
