### ISSUE TITLE
Golden Optics Aimbot | High-Level Documentation [Python Build Update]

### ISSUE THREAD

**Issue by krampus-nuggets** [mgsweet/Apex-NoRecoil-2021#56]
Hey @mgsweet 

I'm really interested in the golden optics aimbot feature you implemented on the AHK Project. I've done some quick reads around the project and it seemed to have worked better than expected, kudos for the implementation. If possible could you please give me a high-level explanation of the following, you don't need to get into the nitty-gritty of how it works, just a plain explanation:

1. Your detection strategy
2. The post player detection action that was applied
3. Your thoughts on what could have lead to the recent bans

In asking the above, I'd prefer to just have a better high-level overview of the feature than to get into the weeds with AHK using time I do not have. Hopefully leading us to improve it and make it safer for players in future updates.

**Comment by mgsweet** [comment]
**For question one:** 

Do u mean how to detect those red pixels?

There is a function in AHK that can help search colour pixels in a rectangular area. But I think what it does is just scan one by one, left to right. 

**For question 2**

Not so sure what post player detection action means. 

What I did in that golden optics aimbot is:
1. Look for some specific colours in a small area in the centre of the screen. If there is, skip. (to avoid shaking)
2. Look for some specific colours in a bigger area in the centre of the screen. If there is, move the cursor to there gradually.

**For question 3**
1. It does look very like an aimbot (the way how it moves the cursor).
2. Actually I am not so sure what is going on. I created a new test account and tested with that feature and it was banned in level 11. I did pick shotgun with golden optics but didn't kill any people with it. Maybe they can detect whether other processes are searching colours?
3. Maybe the whole script is on their black list. Need more game tests on v1.2.5 to see what is going on:(

**Comment by krampus-nuggets** [comment]
@mgsweet - Thanks for getting back to me. All good, I think that's enough for me to work on.

In regards to the bans, here are my thoughts:

1. UC is a well known forum and there is a chance that the tool got noticed and blacklisted.
2. If its been blacklisted lazily they're most likely just checking for the name. Change the name of the executable and the process to something more authentic, like - **mongod** - and check again if the account gets detected in the same amount of time. If not they're just checking names.
3. If the script still gets detected after changing the names, they're actively checking for it so you'll have to find a way to change the signature of how your script runs. There's a bunch of ways, check out UC for more info. Usually adding junk to the script should help but if you can randomize it at start-up that should be enough.
4. This script is open-source and it might be monitored so whatever update you do will be detected soon if enough.
