### ISSUE TITLE
Unable to connect (code:snake)

### ISSUE THREAD

**Issue by bakteribaik** [mgsweet/Apex-NoRecoil-2021#57]
so i use your sofware, 1-3 times game is fine, but game by game i got crashed, and try to restart my pc, when im relogin apex, i got unable to connect(code:snake). i try to find out what that code mean. and thats code is for whos palying apex and detected for cheating. thanks

**Comment by BigSlammu** [comment]
2 days ago i test ur sofware uncheking the auto fire  and optic after of finish my first match the game take long time to back to the lobby ( connecting lobby screen ) that take 10min  i close the game when relog game said my acc are banned

**Comment by lookthisline** [comment]
Me too, just now, Barned

**Comment by filen1** [comment]
after my first 2 accs got banned (high headshot %) still no ban, Just got diamond in arenas using ironically only non shotgun gold sight weapons. I use the raw AHK files instead of the exe since its less detectable.

**Comment by mgsweet** [comment]
Maybe it's time to archive this project lol. I will take a look at how to generate a unique signature for everyone. And also will take a look at what exactly I should do to merge that the ahkhider into the script.

**Comment by hitch3ns** [comment]
> Maybe it's time to archive this project lol. I will take a look at how to generate a unique signature for everyone. And also will take a look at what exactly I should do to merge that the ahkhider into the script.

i like running them without exe just ahk hider then the script 2 small steps but been working great for me in last 2-3 seasons keeping it this way not bad thing

**Comment by bakteribaik** [comment]
> 2 days ago i test ur sofware uncheking the auto fire and optic after of finish my first match the game take long time to back to the lobby ( connecting lobby screen ) that take 10min i close the game when relog game said my acc are banned

yea, my first account got banned because i check the gold optic, and my second account got "Unable to connect (code:snake)" because i use the latest file, and my game always crash after that.

**Comment by krampus-nuggets** [comment]
> Maybe it's time to archive this project lol. I will take a look at how to generate a unique signature for everyone. And also will take a look at what exactly I should do to merge that the ahkhider into the script.

I checked the original repo for hyde.dll and it seems the code has never been open-sourced so it should be good to incorporate into the project in the beginning. If this project is being monitored by the anti-cheat team then it'll be good to start work on an internal-only obfuscator for the script that is not open-sourced in order to hinder detection. Sounds interesting so you can count me in for help if you want.

Original hyde.dll repo - [Link](https://github.com/imm0r/hideProcess)
Updated UC hyde.dll repo - [Link](https://github.com/KIiment/secret-ahk-script/tree/master)

**Comment by mgsweet** [comment]
@krampus-nuggets Yes, you can do some research on them. I am now a busy wage slave and only have time on weekends. What I plan to do is:

First, auto-generate some dummy code to the script to possibly change its file signature.
Then, find out what those dll calls do in the ahkhider and merge them into my script.

**Comment by mgsweet** [comment]
Check https://github.com/mgsweet/Apex-NoRecoil-2021/issues/69.
