### ISSUE TITLE
客户端中的游戏账户已被禁封：Banned

### ISSUE THREAD

**Issue by xyxywan** [mgsweet/Apex-NoRecoil-2021#58]
今天第一把，之前一直玩的港服，今天和室友刚进入地图就被踢了，还没有开枪。没有用过霰弹枪锁定的功能，最近一直在用压枪宏。

**Comment by VStorm001** [comment]
用V1.2.3仍没事(.ahk , .exe)，未使用ahkhider

**Comment by xyxywan** [comment]
可惜了我充值的60块

**Comment by VStorm001** [comment]
> 刚进入地图就被踢了～

可以买个黑号测是否被锁机码

**Comment by xyxywan** [comment]
ea给我发邮件了，说我已经被永久封禁，不过小号还可以正常进入游戏

**Comment by xyxywan** [comment]
@VStorm001 我刚注册的小号用旧版本apexmaster-v1.2.3.exe，玩了两三把之后也被封了，注意安全

**Comment by mgsweet** [comment]
# 目前看来
- 那些对代码进行过修改的，基本没事（除了有个例子是过份依赖金镜 aimbot 被封了）
- 用 `AHK/` 目录下的 `.exe` 的大概率出事。（被封了个11级的个人测试号）
- 用 `AHK/bin` 目录下的 `.exe` 基本不会有事（我自己所有号都是怎么用的，也可能是我自己做过本地一点修改的缘故？）
- 用 ahk + ahkhider 的反映没事

# 总结
- 可能是文件签名的问题，大家可以随便在代码里加点案件改改version什么的（不影响主体逻辑的修改），然后自行用自己觉得最安全的方式运行。
- 注意单单改文件名字是没用的，签名不会变。只改注释也没用。

# 未来规划
再挣扎一下，不行就删库跑路

**Comment by 233Isaac** [comment]
是不是识别算法被小蓝熊搞了

**Comment by 233Isaac** [comment]
![批注 2021-12-07 144118](https://user-images.githubusercontent.com/22152988/144979464-b0770eea-fcff-43e9-858b-b7d31bbf3bd0.png)
听说是这样的  导致自动识别会封号 建议大佬整一个按键切枪的吧 比如说小键盘啥的

**Comment by ricerin** [comment]
一直用的ahk没啥问题，感觉是exe的问题

**Comment by mgsweet** [comment]
v1.2.6  添加了一些新的安全机制，将关闭这些issue看看新版本有没人被ban
