### ISSUE TITLE
Support for 1366x768?

### ISSUE THREAD

**Issue by mello1728** [mgsweet/Apex-NoRecoil-2021#59]
Its a popular resolution and ive tried to get it working but i cant seem to get to add it myself

**Comment by bubbykong** [comment]
support for 21:9 (3440x1440)?

**Comment by mgsweet** [comment]
Did u follow all the steps I mentions in my Youtube tutorial?
If the answer is yes, which step are you stuck in?

**Comment by mello1728** [comment]
yeah i tried to follow the steps, i did the rough generation and pasted it in, uncommented the hint method line but whenever i pick up any gun and press 1 or 2 or E it doesnt detect it it just doesnt say anything
idk if its something to do with the script or like if i need to change the color for the weapon ammo

**Comment by mgsweet** [comment]
@mello1728 that means the pixel positions for weapon1 and weapon2 are wrong. Check https://github.com/mgsweet/Apex-NoRecoil-2021/issues/27 to see where to capture pixel pos for weapon1 and weapon2.

**Comment by mgsweet** [comment]
will support this in v1.2.6
