### ISSUE TITLE
in python project,I found that the relative position is not exactly equal to the (relative_position+1)/2

### ISSUE THREAD

**Issue by chouchoudhunter** [mgsweet/Apex-NoRecoil-2021#63]
Does anybody have any ideas about this conversion
![1](https://user-images.githubusercontent.com/39158588/146554616-4a0e167c-4168-4f2f-802f-921c2ae82fe8.png)

**Comment by chouchoudhunter** [comment]
I have found the reason,
in desktop: the sensitivity in the desktop mouse Settings and the option to improve pointer accuracy and the desktop text zoom affect the movement distance
in game: FOV and in-game sensitivity Settings affect movement distance

**Comment by mgsweet** [comment]
This issue seems to be solved.
