### ISSUE TITLE
希望指导或者添加2560x1600，感谢！

### ISSUE THREAD

**Issue by xtronaltic** [mgsweet/Apex-NoRecoil-2021#64]
您好， Mgsweet，

我刚刚使用您的作品，目前是AHK + hider，按您的视频指导，尝试修改分辨率一直未能成功，不知是哪里出了问题：

1. Windows桌面分辨率改为2560x1600，缩放改成100%
2. Python用debug内的py文件，生成新分辨率数据
3. 创建新ini文件并导入生成的数据，存放至src\resolution，改名字为2560x1600.ini
4. 修改gui.ahk，添加2560x1600
5. 修改AHK\src下的settings为分辨率2560x1600，修改sens和ads和游戏内一致，所有其他选项，包括ads only和auto fire，全部为0，因为游戏内是toggle瞄准
6. 复制ahkhider.ahk, hyde.dll, hyde64.dll至AHK\src下
7. 创建新AHK脚本命名run，并添加
run ahkhider.ahk
run apexmaster.ahk
8. 管理员权限运行run脚本
9. 游戏内fireing range不生效

测试下来，只有settings改1680x1050，游戏内设置1680x1050，只有这个能生效。

不知道是哪步做错了，兄弟，请知道，或者你可以在下个版本中支持一下吗？谢谢

**Comment by mgsweet** [comment]
你可以发个 Pull Request 给我，我可以帮你看看

**Comment by xtronaltic** [comment]
不知道是不是操作正确，我forked你的repo，上传了2560x1600.ini，然后创建了pull request。 这是链接https://github.com/xtronaltic/Apex-NoRecoil-2021/tree/main/AHK/src/resolution，如果我没pull request成功，您有空帮我看一下，谢谢

**Comment by mgsweet** [comment]
帮不了你，我发现我的显示器不支持你的这个分辨率。

**Comment by xtronaltic** [comment]
嗯，我的是16:10

**Comment by mgsweet** [comment]
或许这个视频可以帮到你：https://www.youtube.com/watch?v=wYyIMbdagw4

**Comment by xtronaltic** [comment]
我联系了视频的作者，他远程帮我看了一下，是ahk_resolution_rough_generator.py生成的数据和2560x1600兼容性不完美导致的，在resolution文件夹里，手动改.ini文件每个枪的坐标，可以生效。

**Comment by jayking999** [comment]
> 我联系了视频的作者，他远程帮我看了一下，逐步排查是ahk_resolution_rough_generator.py生成的数据和2560x1600兼容性不完美导致的，在resolution文件夹里，手动改.ini文件每个枪的坐标，可以生效。

 817,689"
"897,687?为什么我的仍然不生效
