### ISSUE TITLE
我想知道武器像素检测点在哪里 I want to know where the weapon pixel detection point is

### ISSUE THREAD

**Issue by Yenro** [mgsweet/Apex-NoRecoil-2021#67]
我正在制作720p分辨率的脚本，我在编辑R99、哈沃克、平行步枪时调整了许多次依然识别不到，我想知道这几种武器像素检测点在哪里，谢谢
I am making a script for 720p resolution, I have adjusted many times in editing R99, Havok, parallel rifle still not recognized, I want to know where these weapons pixel detection points are, thanks bro

**Comment by mgsweet** [comment]
1280 * 720 现在已经支持了
