### ISSUE TITLE
v1.2.6 AHK-Build | Release

### ISSUE THREAD

**Issue by mgsweet** [mgsweet/Apex-NoRecoil-2021#69]
https://github.com/mgsweet/Apex-NoRecoil-2021/releases/tag/AHK-v1.2.6

- built-in hider
- support 1280*720
- support 1366*768
- add a UUID generator to help change the file signature

**Comment by mgsweet** [comment]
The UUID generator would do a slight change to the script to change the file signature.

**Comment by mgsweet** [comment]
@all-contributors please add @thirdpetros for data

**Comment by L0thric-HM** [comment]
Tested for the last 4 days. Ban status: not banned.

**Comment by mgsweet** [comment]
Need testing:
1. Run the exe file in `AHK/` directly (no change to UUID)
2. Gen new UUID, compile them and run those `.exe`. (I am testing, no ban yet)
3. Gen new UUID and run `.ahk` directly.

**Comment by VStorm001** [comment]
最近设置了第二个萤幕，我该如何让脚本在主萤幕上运行？

**Comment by BamaBinBombin** [comment]
https://imgur.com/a/CwUbg9h
lag once scripts weapon detect starts as of last patch.
