### ISSUE TITLE
现阶段只有.ahk档能用？

### ISSUE THREAD

**Issue by VStorm001** [mgsweet/Apex-NoRecoil-2021#71]
加了UUID的执行档能用吗？

**Comment by mgsweet** [comment]
换了 uuid 你需要自行编译
但我希望有人去测试下 AHK/ 下的 exe 能不能用，我自己换了 uuid 的本地版本目前都没什么问题。所有都内嵌了hider的

**Comment by jayking999** [comment]
编辑了UUIDpy文件对exe修改时,报编码类型不符

**Comment by mgsweet** [comment]
> 编辑了UUIDpy文件对exe修改时,报编码类型不符

编译后只有机器能理解了，无法做正则匹配，你需要先生成uuid再编译
