### ISSUE TITLE
GeForce NOW

### ISSUE THREAD

**Issue by Aumopko** [mgsweet/Apex-NoRecoil-2021#74]
Does it work on GeForce NOW?

**Comment by hitch3ns** [comment]
well i don't see why not, since the AHK detect certain colors on the screen in full screenmode if you have Gforce on pc full screen i believe it would still works

**Comment by Aumopko** [comment]
I don't know if I did it wrong or what, it didn't work

**Comment by mgsweet** [comment]
Cannot help. Not a member of GeForce NOW.
