### ISSUE TITLE
Breaks Automatic Rifles

### ISSUE THREAD

**Issue by krampus-nuggets** [mgsweet/Apex-NoRecoil-2021#8]
Hi there, I've been trying to debug the issue myself but who better to help than the source.

Basically, when the script is run it turns the Automatic Rifles into Single-Shot Rifles. If you tap the left-click mouse button a couple of times it'll shoot automatically but usually it will only shoot one shot if the script is running.

Video - https://res.cloudinary.com/kitsheaven-inc/video/upload/v1629008208/uc-shit/apex-no-recoil_omg9vt.mp4

**Note** - Video link above updated

**Comment by mgsweet** [comment]
@krampus-nuggets Hi, could you help me take a look at whether your problem is solved  in the latest update? I know the single fire mode op was a bit buggy previously.

**Comment by krampus-nuggets** [comment]
@mgsweet - I tested now and it doesn't hard-lock the AR weapons from the start anymore. However it still happens randomly. You'd have to click about three times before it actually shoots full-auto again.

Can I request you split the single-shot functionality that you added to a different branch with another version of the script that works without issue on AR weapons then I could potentially help debug a bit faster.

**Comment by mgsweet** [comment]
@krampus-nuggets I will do this tonight. thx:)

**Comment by krampus-nuggets** [comment]
@mgsweet - Thanks, I'll have a look. In the mean time I've rewritten your AHK script in Python. It's my primary language, I'm not too familiar AHK. You can check it out on this branch of my fork in the python directory:

* https://github.com/krampus-nuggets/Apex-NoRecoil-2021/tree/python-build

What has been implemented:

* Recoil patterns for R-301 and R-99 | For testing
* Google's Tesseract OCR for weapon recognition
* Apply OCR detection directly to dictionary key as to limit time spent on IF/ELSE conditional statements
* Weapon switching and applying new recoil patterns
* Disable and Enable recoil-control via DEL key

To-be implemented:

* CLI functionality
* Additional recoil patterns
* EXE release build pipeline
* Single-Shot weapon functionality

At the moment it's pretty stable and works as expected. I'm interested to see what happens when applying the single-shot functionality.

I know it's overkill but I was low-key having fun working on this lol

**Comment by mgsweet** [comment]
You can create a pull request and become a contributor to this project :)

**Comment by krampus-nuggets** [comment]
@mgsweet - First stable build finished and pull request submitted. Could you possibly provide any documentation of how you've been generating recoil patterns. I'm attempting to build a tool that could help generate patterns and any additional info would help speed up the process.

**Comment by mgsweet** [comment]
@krampus-nuggets Actually I don't have my own pattern. A guy sent me his patten through email and what I did is just parse it to my the format I want. Yes, I am also thinking of building a tool to track the pattern. It may need more works than building this script itself. But it would be cool. Didn't come out with an idea of how to build that. Too much work these days. You can have a try and send me your latest update. Respect!

**Comment by filen1** [comment]
@krampus-nuggets @mgsweet See Issue #11 

What could be useful is a python script for notepad++ to delete anything past the hundredth mark of the resulting pattern (or even make it conform to script layout). This would streamline it and make it much easier to create new patterns. One thing to note is no matter what we do the patterns we create can never be 100% accurate as every guns spray pattern has some RNG variance.

**Comment by krampus-nuggets** [comment]
I've mostly been using and working on the Python Build of this project so this is now a non-issue for me. Since no-one else has brought up any problems regarding what I've stated here I will be closing this issue.
