### ISSUE TITLE
2 things which should be fixed.

### ISSUE THREAD

**Issue by Igors7999** [mgsweet/Apex-NoRecoil-2021#80]
1) Can you make a better recoil for hemlok? It's really hard to shoot with 2-4 optics. And can you make autofire for hemlok single fire? 

2) Can you add fov recoil pattern adaptation?  It is more convenient to play with fov 110. but if you apply it with the standard script settings, the recoil will be quite strong.

**Comment by mgsweet** [comment]
1. I think there is autofire for hemlok single fire. I personally do not participate in making those patterns. I did try to use AE to create some better recoil patterns but failed.

2. Yes, will take a look at it in the next version.

**Comment by mgsweet** [comment]
@Igors7999 Is there a ready-made formula to convert the relationship between fov and sens?

**Comment by mgsweet** [comment]
Not enough knowledge to fix...
