### ISSUE TITLE
Issues about python version

### ISSUE THREAD

**Issue by I-nsAnity** [mgsweet/Apex-NoRecoil-2021#81]
我个人写了一个相似的版本，通过我自己训练的字库检测简中枪名实现切换，基本实现完美识别。但我的脚本只实现了中距离压枪，对于高倍镜的左右跳动补偿效果并不好，同时我使用您pattern文件夹里的数据出现压枪幅度过大的情况。

我也使用move(x,y)之后sleep的方法，但我直接使用了pyautogui库。
在我外接的arduino模拟鼠标上执行依然幅度过大。

如果您有后续更新python版本的想法，我可以提供traineddata实现简中支持。

**Comment by mgsweet** [comment]
我没有参与过python版本的开发，python版本的维护者应该看不懂中文。python版本目前处于废弃状态，但你可以提pr去帮助他更新。

**Comment by mgsweet** [comment]
For issues with the python script, English is needed. Thanks.
