### ISSUE TITLE
Season 12 Updates

### ISSUE THREAD

**Issue by hitch3ns** [mgsweet/Apex-NoRecoil-2021#83]
Hello :) hope you having good time, 

couple of things require updates now ( whenever you get the chance ) 

Update weapons: 

alternator is now back light ammo weapon out of care package
Volt is now a care package weapon

do we need this changes for proper detection right ?

**Comment by youngdeag** [comment]
Could you add 1440 x 1080 mgsweet?
There is no custom resolution for 4:3, I've tried making it but have found some complications.
Maybe for the next update?

**Comment by VStorm001** [comment]
~
> do we need this changes for proper detection right ?

yap

**Comment by cherrypapa** [comment]
Can you post an EXE version?
