### ISSUE TITLE
4:3 1440x1080

### ISSUE THREAD

**Issue by youngdeag** [mgsweet/Apex-NoRecoil-2021#87]
Add support for 1440 x 1080?
4:3 resolution support

**Comment by RicckSanchez** [comment]
Pretty sure they haven't pushed any 4:3 res cause it's not possible.
I just looked and there is no 4:3 rip

**Comment by mgsweet** [comment]
Ask for help here: https://github.com/mgsweet/Apex-NoRecoil-2021/issues/127
