### ISSUE TITLE
可以入选21世纪最无用的外挂

### ISSUE THREAD

**Issue by JesseWeb** [mgsweet/Apex-NoRecoil-2021#88]
说个笑话: apex的Recoil

**Comment by REOSIR** [comment]
Have fun

**Comment by mgsweet** [comment]
No one fucking cares about whether you want to use it or not. If it is useless, it would not get more than 100 stars. It's obvious that you are the joke. Don't be like a clown only knowing to say some bullshit.

**Comment by JesseWeb** [comment]
> 
oh well. looks like you having a issue with your mine.
100 starts only prove that there is more than 100 momless kids are ruining this game and they gaming life by using the EXE that you build. and you look very proud of that which is sad for you.
you must had very sad childhood.
im sorry about that. hope you have wonderful life.






























**JUST EAT MY SHIT YOU SUSSY BAKA!!!**
