### ISSUE TITLE
Detected ?

### ISSUE THREAD

**Issue by SomeNameCreated** [mgsweet/Apex-NoRecoil-2021#90]
I saw many comments on UnknownCheats site that AHK is detected this season. I am interested if thats true cause i was using it from the start of new season for like 4hours a day and i  didnt get banned, so i dont know if people used it very blatant so it was easy to spot or it really got detected and i got lucky. One guy said that u are going to get banned if someone report u and not by having it running in the background, but others said they got banned just by using it for only 2hr. Right now i am not using it to even test it if its true cause i rather be save and sure its undetected and they were stupid with how they were using it, because if get banned hwid i dont know shit how to make it so i can play again

**Comment by CoolOldBoomer** [comment]
Since the start of new season I been playing 5-7 hours a day with it. Even using rapid fire enabled. From the comments that I read, some don't go into much detail as in if they are running the ahk and the py together. And if they even complied it. You can wait for couple of weeks for an update or just play without it for while.

**Comment by SomeNameCreated** [comment]
I will just play without it for a 2-3 days to see how thing go

**Comment by Nekomimis** [comment]
I mean, controlling recoil isn't _too hard_per se. There's jitter aiming. Been using it right after S12 started. This script is mainly for controlling recoils so you'd still miss your shots. Then again, nothing's safe hence the reason use at your own risk. Got banned on my main bcos I accidentally started up the .exe by accident.

**Comment by Bmw49** [comment]
Im still using 1.2.5 im not banned

**Comment by turaki0423** [comment]
playing with 1.2.8 and got banned within 1 hours on an account that has not played apex for at least 4 months

**Comment by SomeNameCreated** [comment]
> playing with 1.2.8 and got banned within 1 hours on an account that has not played apex for at least 4 months

Then u did something wrong cause i am already playing with it 5 days and every day for 5 hours straight and didnt get banned

**Comment by turaki0423** [comment]
> > playing with 1.2.8 and got banned within 1 hours on an account that has not played apex for at least 4 months
> 
> Then u did something wrong cause i am already playing with it 5 days and every day for 5 hours straight and didnt get banned

i'm afraid not 'cause i was playing on reinstalled Windows 11 with Defender uninstalled.

**Comment by SomeNameCreated** [comment]
> > > playing with 1.2.8 and got banned within 1 hours on an account that has not played apex for at least 4 months
> > 
> > 
> > Then u did something wrong cause i am already playing with it 5 days and every day for 5 hours straight and didnt get banned
> 
> i'm afraid not 'cause i was playing on reinstalled Windows 11 with Defender uninstalled.

So yeah I am just lucky and not getting banned ok

**Comment by zcjiecao** [comment]
Version 1.28, when I officially used it in the game, I first encountered a system crash and input lag, and then my account was banned by ea about an hour later

**Comment by mgsweet** [comment]
see https://github.com/mgsweet/Apex-NoRecoil-2021/issues/92
