### ISSUE TITLE
banned for using 1.2.8？

### ISSUE THREAD

**Issue by meik12138** [mgsweet/Apex-NoRecoil-2021#92]
I was banned after about half an hour with version 1.2.8, but had no problems with version 1.2.7, which had no converters or Volt gun

**Comment by zcjiecao** [comment]
me too.When I officially used the game, I first encountered a system crash and input lag, and then my account was banned by ea about an hour later.

**Comment by mgsweet** [comment]
ahk or exe? with your own uuid?

**Comment by meik12138** [comment]
> 

with ahk  and i use the hideuuid program which in the file before start this：（

**Comment by VStorm001** [comment]
> with ahk  and i use the hideuuid program which in the file before start this：（

Hide uuid or change uuid?
I run v1.2.8 without hide program,still safely.

**Comment by deanugbu** [comment]
I was also banned using 1.2.8 used the exe. opened the program pressed save and run got on apex and one game i was banned

**Comment by mgsweet** [comment]
If u don't know how to make an exe,  use ahk with your own uuid. I have removed all the exe from release. Those released exe files are obviously on EA's blacklist. I am using my own exe for my main account and no ban so far.
