### ISSUE TITLE
Pattern creation 

### ISSUE THREAD

**Issue by hitch3ns** [mgsweet/Apex-NoRecoil-2021#95]
i found this emulation for pattern not sure if it could be helpful for pattern creation 

https://apexlegendsrecoils.online/

**Comment by krampus-nuggets** [comment]
Here's the values they use: 

* [Raw Recoil Values](https://github.com/metaflow/apex-recoil/blob/main/client/raw_recoils.json)
* [Per Weapon Values](https://github.com/metaflow/apex-recoil/blob/main/client/specs.json)

It seems to compensate for added mods as well, pretty cool.

**Comment by BamaBinBombin** [comment]
Any idea how to convert that into the 'pattern' format that is used in this app?  I looked it over, it seems like it might be values set to a .1 sensitivity, but even then, it seems a bit odd...
